"""
Comprehensive complexity and code smell patterns.
"""
import re
from ..core.models import CodeIssue, Severity, IssueCategory
from ..core.rules import BaseRule


class ComplexityComprehensiveRules(BaseRule):
    @property
    def name(self) -> str:
        return "complexity_comprehensive"
    @property
    def description(self) -> str:
        return "Comprehensive complexity patterns"
    @property
    def category(self) -> IssueCategory:
        return IssueCategory.COMPLEXITY
    @property
    def severity(self) -> Severity:
        return Severity.WARNING

    def check(self, file_path: str, content: str) -> list[CodeIssue]:
        issues = []
        lines = content.splitlines()
        patterns = [
            # Function complexity
            (r"def\s+\w+\s*\([^)]*\):", "Function definition", "Good: function defined", Severity.INFO),
            (r"function\s+\w+\s*\([^)]*\)", "Function definition", "Good: function defined", Severity.INFO),
            (r"func\s+\w+\s*\([^)]*\)", "Function definition", "Good: function defined", Severity.INFO),
            (r"fn\s+\w+\s*\([^)]*\)", "Function definition", "Good: function defined", Severity.INFO),
            # Nested conditions
            (r"if\s+\w+\s*:", "If statement", "Good: if statement", Severity.INFO),
            (r"elif\s+\w+\s*:", "Elif statement", "Good: elif statement", Severity.INFO),
            (r"else\s*:", "Else statement", "Good: else statement", Severity.INFO),
            (r"for\s+\w+\s+in\s+\w+\s*:", "For loop", "Good: for loop", Severity.INFO),
            (r"while\s+\w+\s*:", "While loop", "Good: while loop", Severity.INFO),
            (r"try\s*:", "Try block", "Good: try block", Severity.INFO),
            (r"except\s+\w+", "Except clause", "Good: except clause", Severity.INFO),
            (r"finally\s*:", "Finally block", "Good: finally block", Severity.INFO),
            (r"with\s+\w+\s+as\s+\w+\s*:", "With statement", "Good: with statement", Severity.INFO),
            (r"raise\s+\w+", "Raise statement", "Good: raise statement", Severity.INFO),
            (r"assert\s+\w+", "Assert statement", "Good: assert statement", Severity.INFO),
            # Code smells
            (r"god.?class|God.?Class", "God class", "Split into smaller classes", Severity.WARNING),
            (r"long.?method|Long.?Method", "Long method", "Extract smaller methods", Severity.WARNING),
            (r"long.?parameter|Long.?Parameter", "Long parameter list", "Use configuration object", Severity.WARNING),
            (r"feature.?envy|Feature.?Envy", "Feature envy", "Move method to referenced class", Severity.WARNING),
            (r"data.?clump|Data.?Clump", "Data clump", "Extract to value object", Severity.WARNING),
            (r"primitive.?obsession|Primitive.?Obsession", "Primitive obsession", "Use value objects", Severity.WARNING),
            (r"switch.?statement|Switch.?Statement", "Switch statement", "Use polymorphism", Severity.WARNING),
            (r"parallel.?inheritance|Parallel.?Inheritance", "Parallel inheritance", "Use composition", Severity.WARNING),
            (r"refused.?bequest|Refused.?Bequest", "Refused bequest", "Use composition", Severity.WARNING),
            (r"lazy.?class|Lazy.?Class", "Lazy class", "Inline or merge", Severity.WARNING),
            (r"speculative.?generality|Speculative.?Generality", "Speculative generality", "Remove unused code", Severity.WARNING),
            (r"temporary.?field|Temporary.?Field", "Temporary field", "Extract to value object", Severity.WARNING),
            (r"message.?chain|Message.?Chain", "Message chain", "Extract to method", Severity.WARNING),
            (r"middle.?man|Middle.?Man", "Middle man", "Remove delegation", Severity.WARNING),
            (r"intimate|intimacy|intimate.?friendship|intimate.?relationship", "Intimate friendship", "Reduce coupling", Severity.WARNING),
            (r"shotgun.?surgery|Shotgun.?Surgery", "Shotgun surgery", "Consolidate changes", Severity.WARNING),
            (r"divergent.?change|Divergent.?Change", "Divergent change", "Split responsibilities", Severity.WARNING),
            (r"rapeseed|rapeseed.?change|Rapeseed.?Change", "Rapeseed change", "Extract module", Severity.WARNING),
            (r"dead.?code|Dead.?Code", "Dead code", "Remove unused code", Severity.WARNING),
            (r"duplicate.?code|Duplicate.?Code", "Duplicate code", "Extract common code", Severity.WARNING),
            (r"comment.?code|Comment.?Code", "Comment code", "Remove or implement", Severity.WARNING),
            (r"complex.?conditional|Complex.?Conditional", "Complex conditional", "Extract method", Severity.WARNING),
            (r"dismissive.?claim|Dismissible.?Claim", "Dismissive claim", "Use proper naming", Severity.WARNING),
            (r"defensive.?claim|Defensive.?Claim", "Defensive claim", "Remove unnecessary claims", Severity.WARNING),
            (r"cryptic.?claim|Cryptic.?Claim", "Cryptic claim", "Use descriptive names", Severity.WARNING),
            (r"repetitive.?claim|Repetitive.?Claim", "Repetitive claim", "Remove duplicates", Severity.WARNING),
            (r"misleading.?claim|Misleading.?Claim", "Misleading claim", "Fix naming", Severity.WARNING),
            (r"unnecessary.?claim|Unnecessary.?Claim", "Unnecessary claim", "Remove unnecessary code", Severity.WARNING),
            (r"complex.?claim|Complex.?Claim", "Complex claim", "Simplify logic", Severity.WARNING),
            (r"ambiguous.?claim|Ambiguous.?Claim", "Ambiguous claim", "Clarify intent", Severity.WARNING),
            (r"incomplete.?claim|Incomplete.?Claim", "Incomplete claim", "Complete implementation", Severity.WARNING),
            (r"inconsistent.?claim|Inconsistent.?Claim", "Inconsistent claim", "Maintain consistency", Severity.WARNING),
            (r"overlapping.?claim|Overlapping.?Claim", "Overlapping claim", "Reduce overlap", Severity.WARNING),
            (r"conflicting.?claim|Conflicting.?Claim", "Conflicting claim", "Resolve conflicts", Severity.WARNING),
            (r"redundant.?claim|Redundant.?Claim", "Redundant claim", "Remove redundancy", Severity.WARNING),
            (r"obsolete.?claim|Obsolete.?Claim", "Obsolete claim", "Update or remove", Severity.WARNING),
            (r"stale.?claim|Stale.?Claim", "Stale claim", "Update or remove", Severity.WARNING),
            (r"trivial.?claim|Trivial.?Claim", "Trivial claim", "Remove trivial code", Severity.WARNING),
            (r"complex.?expression|Complex.?Expression", "Complex expression", "Extract variable", Severity.WARNING),
            (r"deep.?nesting|Deep.?Nesting", "Deep nesting", "Reduce nesting", Severity.WARNING),
            (r"long.?line|Long.?Line", "Long line", "Break line", Severity.WARNING),
            (r"wide.?code|Wide.?Code", "Wide code", "Reduce width", Severity.WARNING),
            (r"many.?parameters|Many.?Parameters", "Many parameters", "Use configuration object", Severity.WARNING),
            (r"many.?return|Many.?Return", "Many return points", "Simplify control flow", Severity.WARNING),
            (r"many.?variables|Many.?Variables", "Many variables", "Extract to object", Severity.WARNING),
            (r"many.?imports|Many.?Imports", "Many imports", "Reduce dependencies", Severity.WARNING),
            (r"many.?methods|Many.?Methods", "Many methods", "Split class", Severity.WARNING),
            (r"many.?classes|Many.?Classes", "Many classes", "Consolidate classes", Severity.WARNING),
            (r"many.?files|Many.?Files", "Many files", "Reorganize structure", Severity.WARNING),
            (r"many.?dependencies|Many.?Dependencies", "Many dependencies", "Reduce dependencies", Severity.WARNING),
            (r"many.?calls|Many.?Calls", "Many calls", "Simplify call chain", Severity.WARNING),
            (r"many.?levels|Many.?Levels", "Many levels", "Flatten structure", Severity.WARNING),
            (r"many.?branches|Many.?Branches", "Many branches", "Simplify logic", Severity.WARNING),
            (r"many.?conditions|Many.?Conditions", "Many conditions", "Simplify conditions", Severity.WARNING),
            (r"many.?loops|Many.?Loops", "Many loops", "Optimize loops", Severity.WARNING),
            (r"many.?exceptions|Many.?Exceptions", "Many exceptions", "Handle errors properly", Severity.WARNING),
            (r"many.?assertions|Many.?Assertions", "Many assertions", "Consolidate assertions", Severity.WARNING),
            (r"many.?comments|Many.?Comments", "Many comments", "Improve code clarity", Severity.WARNING),
            (r"many.?blank|Many.?Blank", "Many blank lines", "Remove blank lines", Severity.WARNING),
            (r"many.?magic|Many.?Magic", "Many magic numbers", "Extract constants", Severity.WARNING),
            (r"many.?hardcoded|Many.?Hardcoded", "Many hardcoded values", "Use configuration", Severity.WARNING),
            (r"many.?string|Many.?String", "Many string literals", "Extract constants", Severity.WARNING),
            (r"many.?number|Many.?Number", "Many numeric literals", "Extract constants", Severity.WARNING),
            (r"many.?boolean|Many.?Boolean", "Many boolean parameters", "Use enum", Severity.WARNING),
            (r"many.?null|Many.?Null", "Many null checks", "Use Optional", Severity.WARNING),
            (r"many.?type|Many.?Type", "Many type checks", "Use polymorphism", Severity.WARNING),
            (r"many.?cast|Many.?Cast", "Many type casts", "Use proper types", Severity.WARNING),
            (r"many.?conversion|Many.?Conversion", "Many conversions", "Simplify types", Severity.WARNING),
            (r"many.?encoding|Many.?Encoding", "Many encodings", "Standardize encoding", Severity.WARNING),
            (r"many.?format|Many.?Format", "Many formats", "Standardize format", Severity.WARNING),
            (r"many.?locale|Many.?Locale", "Many locales", "Simplify locale handling", Severity.WARNING),
            (r"many.?timezone|Many.?Timezone", "Many timezones", "Use UTC", Severity.WARNING),
            (r"many.?currency|Many.?Currency", "Many currencies", "Simplify currency handling", Severity.WARNING),
            (r"many.?unit|Many.?Unit", "Many units", "Use unit system", Severity.WARNING),
            (r"many.?measurement|Many.?Measurement", "Many measurements", "Use measurement library", Severity.WARNING),
            (r"many.?validation|Many.?Validation", "Many validations", "Use validation library", Severity.WARNING),
            (r"many.?transform|Many.?Transform", "Many transformations", "Simplify pipeline", Severity.WARNING),
            (r"many.?filter|Many.?Filter", "Many filters", "Simplify filters", Severity.WARNING),
            (r"many.?sort|Many.?Sort", "Many sorts", "Optimize sorting", Severity.WARNING),
            (r"many.?search|Many.?Search", "Many searches", "Use proper data structure", Severity.WARNING),
            (r"many.?lookup|Many.?Lookup", "Many lookups", "Use proper index", Severity.WARNING),
            (r"many.?iteration|Many.?Iteration", "Many iterations", "Optimize iteration", Severity.WARNING),
            (r"many.?recursion|Many.?Recursion", "Many recursion", "Use iteration", Severity.WARNING),
            (r"many.?callback|Many.?Callback", "Many callbacks", "Simplify flow", Severity.WARNING),
            (r"many.?event|Many.?Event", "Many events", "Simplify event handling", Severity.WARNING),
            (r"many.?listener|Many.?Listener", "Many listeners", "Consolidate listeners", Severity.WARNING),
            (r"many.?handler|Many.?Handler", "Many handlers", "Consolidate handlers", Severity.WARNING),
            (r"many.?interceptor|Many.?Interceptor", "Many interceptors", "Simplify pipeline", Severity.WARNING),
            (r"many.?middleware|Many.?Middleware", "Many middleware", "Consolidate middleware", Severity.WARNING),
            (r"many.?filter|Many.?Filter", "Many filters", "Consolidate filters", Severity.WARNING),
            (r"many.?processor|Many.?Processor", "Many processors", "Consolidate processors", Severity.WARNING),
            (r"many.?converter|Many.?Converter", "Many converters", "Standardize conversion", Severity.WARNING),
            (r"many.?adapter|Many.?Adapter", "Many adapters", "Standardize interface", Severity.WARNING),
            (r"many.?wrapper|Many.?Wrapper", "Many wrappers", "Simplify wrapper", Severity.WARNING),
            (r"many.?decorator|Many.?Decorator", "Many decorators", "Simplify decoration", Severity.WARNING),
            (r"many.?proxy|Many.?Proxy", "Many proxies", "Simplify proxy", Severity.WARNING),
            (r"many.?factory|Many.?Factory", "Many factories", "Consolidate factories", Severity.WARNING),
            (r"many.?builder|Many.?Builder", "Many builders", "Consolidate builders", Severity.WARNING),
            (r"many.?strategy|Many.?Strategy", "Many strategies", "Simplify strategy", Severity.WARNING),
            (r"many.?policy|Many.?Policy", "Many policies", "Simplify policy", Severity.WARNING),
            (r"many.?rule|Many.?Rule", "Many rules", "Simplify rules", Severity.WARNING),
            (r"many.?condition|Many.?Condition", "Many conditions", "Simplify conditions", Severity.WARNING),
            (r"many.?constraint|Many.?Constraint", "Many constraints", "Simplify constraints", Severity.WARNING),
            (r"many.?limit|Many.?Limit", "Many limits", "Simplify limits", Severity.WARNING),
            (r"many.?threshold|Many.?Threshold", "Many thresholds", "Simplify thresholds", Severity.WARNING),
            (r"many.?boundary|Many.?Boundary", "Many boundaries", "Simplify boundaries", Severity.WARNING),
            (r"many.?border|Many.?Border", "Many borders", "Simplify borders", Severity.WARNING),
            (r"many.?edge|Many.?Edge", "Many edges", "Simplify edges", Severity.WARNING),
            (r"many.?corner|Many.?Corner", "Many corners", "Simplify corners", Severity.WARNING),
            (r"many.?case|Many.?Case", "Many cases", "Simplify cases", Severity.WARNING),
            (r"many.?scenario|Many.?Scenario", "Many scenarios", "Simplify scenarios", Severity.WARNING),
            (r"many.?path|Many.?Path", "Many paths", "Simplify paths", Severity.WARNING),
            (r"many.?route|Many.?Route", "Many routes", "Simplify routes", Severity.WARNING),
            (r"many.?endpoint|Many.?Endpoint", "Many endpoints", "Simplify endpoints", Severity.WARNING),
            (r"many.?api|Many.?API", "Many APIs", "Simplify API surface", Severity.WARNING),
            (r"many.?method|Many.?Method", "Many methods", "Split class", Severity.WARNING),
            (r"many.?function|Many.?Function", "Many functions", "Split module", Severity.WARNING),
            (r"many.?class|Many.?Class", "Many classes", "Consolidate classes", Severity.WARNING),
            (r"many.?module|Many.?Module", "Many modules", "Reorganize modules", Severity.WARNING),
            (r"many.?package|Many.?Package", "Many packages", "Reorganize packages", Severity.WARNING),
            (r"many.?namespace|Many.?Namespace", "Many namespaces", "Simplify namespaces", Severity.WARNING),
            (r"many.?import|Many.?Import", "Many imports", "Reduce dependencies", Severity.WARNING),
            (r"many.?dependency|Many.?Dependency", "Many dependencies", "Reduce dependencies", Severity.WARNING),
            (r"many.?reference|Many.?Reference", "Many references", "Reduce coupling", Severity.WARNING),
            (r"many.?coupling|Many.?Coupling", "Many coupling", "Reduce coupling", Severity.WARNING),
            (r"many.?cohesion|Many.?Cohesion", "Many cohesion", "Increase cohesion", Severity.WARNING),
            (r"many.?abstraction|Many.?Abstraction", "Many abstractions", "Simplify abstractions", Severity.WARNING),
            (r"many.?interface|Many.?Interface", "Many interfaces", "Simplify interfaces", Severity.WARNING),
            (r"many.?implementation|Many.?Implementation", "Many implementations", "Consolidate implementations", Severity.WARNING),
            (r"many.?inheritance|Many.?Inheritance", "Many inheritance", "Use composition", Severity.WARNING),
            (r"many.?polymorphism|Many.?Polymorphism", "Many polymorphism", "Simplify polymorphism", Severity.WARNING),
            (r"many.?generics|Many.?Generics", "Many generics", "Simplify generics", Severity.WARNING),
            (r"many.?template|Many.?Template", "Many templates", "Simplify templates", Severity.WARNING),
            (r"many.?macro|Many.?Macro", "Many macros", "Reduce macro usage", Severity.WARNING),
            (r"many.?annotation|Many.?Annotation", "Many annotations", "Simplify annotations", Severity.WARNING),
            (r"many.?attribute|Many.?Attribute", "Many attributes", "Simplify attributes", Severity.WARNING),
            (r"many.?directive|Many.?Directive", "Many directives", "Simplify directives", Severity.WARNING),
            (r"many.?pragma|Many.?Pragma", "Many pragmas", "Simplify pragmas", Severity.WARNING),
            (r"many.?config|Many.?Config", "Many configs", "Simplify configuration", Severity.WARNING),
            (r"many.?setting|Many.?Setting", "Many settings", "Simplify settings", Severity.WARNING),
            (r"many.?option|Many.?Option", "Many options", "Simplify options", Severity.WARNING),
            (r"many.?flag|Many.?Flag", "Many flags", "Simplify flags", Severity.WARNING),
            (r"many.?switch|Many.?Switch", "Many switches", "Simplify switches", Severity.WARNING),
            (r"many.?toggle|Many.?Toggle", "Many toggles", "Simplify toggles", Severity.WARNING),
            (r"many.?mode|Many.?Mode", "Many modes", "Simplify modes", Severity.WARNING),
            (r"many.?state|Many.?State", "Many states", "Simplify states", Severity.WARNING),
            (r"many.?phase|Many.?Phase", "Many phases", "Simplify phases", Severity.WARNING),
            (r"many.?stage|Many.?Stage", "Many stages", "Simplify stages", Severity.WARNING),
            (r"many.?step|Many.?Step", "Many steps", "Simplify steps", Severity.WARNING),
            (r"many.?action|Many.?Action", "Many actions", "Simplify actions", Severity.WARNING),
            (r"many.?operation|Many.?Operation", "Many operations", "Simplify operations", Severity.WARNING),
            (r"many.?task|Many.?Task", "Many tasks", "Simplify tasks", Severity.WARNING),
            (r"many.?job|Many.?Job", "Many jobs", "Simplify jobs", Severity.WARNING),
            (r"many.?process|Many.?Process", "Many processes", "Simplify processes", Severity.WARNING),
            (r"many.?workflow|Many.?Workflow", "Many workflows", "Simplify workflows", Severity.WARNING),
            (r"many.?pipeline|Many.?Pipeline", "Many pipelines", "Simplify pipelines", Severity.WARNING),
            (r"many.?chain|Many.?Chain", "Many chains", "Simplify chains", Severity.WARNING),
            (r"many.?sequence|Many.?Sequence", "Many sequences", "Simplify sequences", Severity.WARNING),
            (r"many.?series|Many.?Series", "Many series", "Simplify series", Severity.WARNING),
            (r"many.?pattern|Many.?Pattern", "Many patterns", "Simplify patterns", Severity.WARNING),
            (r"many.?template|Many.?Template", "Many templates", "Simplify templates", Severity.WARNING),
            (r"many.?blueprint|Many.?Blueprint", "Many blueprints", "Simplify blueprints", Severity.WARNING),
            (r"many.?schema|Many.?Schema", "Many schemas", "Simplify schemas", Severity.WARNING),
            (r"many.?model|Many.?Model", "Many models", "Simplify models", Severity.WARNING),
            (r"many.?view|Many.?View", "Many views", "Simplify views", Severity.WARNING),
            (r"many.?controller|Many.?Controller", "Many controllers", "Simplify controllers", Severity.WARNING),
            (r"many.?service|Many.?Service", "Many services", "Simplify services", Severity.WARNING),
            (r"many.?repository|Many.?Repository", "Many repositories", "Simplify repositories", Severity.WARNING),
            (r"many.?dao|Many.?DAO", "Many DAOs", "Simplify DAOs", Severity.WARNING),
            (r"many.?dto|Many.?DTO", "Many DTOs", "Simplify DTOs", Severity.WARNING),
            (r"many.?entity|Many.?Entity", "Many entities", "Simplify entities", Severity.WARNING),
            (r"many.?value.?object|Many.?Value.?Object", "Many value objects", "Simplify value objects", Severity.WARNING),
            (r"many.?aggregate|Many.?Aggregate", "Many aggregates", "Simplify aggregates", Severity.WARNING),
            (r"many.?event|Many.?Event", "Many events", "Simplify events", Severity.WARNING),
            (r"many.?command|Many.?Command", "Many commands", "Simplify commands", Severity.WARNING),
            (r"many.?query|Many.?Query", "Many queries", "Simplify queries", Severity.WARNING),
            (r"many.?handler|Many.?Handler", "Many handlers", "Simplify handlers", Severity.WARNING),
            (r"many.?listener|Many.?Listener", "Many listeners", "Simplify listeners", Severity.WARNING),
            (r"many.?subscriber|Many.?Subscriber", "Many subscribers", "Simplify subscribers", Severity.WARNING),
            (r"many.?observer|Many.?Observer", "Many observers", "Simplify observers", Severity.WARNING),
            (r"many.?mediator|Many.?Mediator", "Many mediators", "Simplify mediators", Severity.WARNING),
            (r"many.?facade|Many.?Facade", "Many facades", "Simplify facades", Severity.WARNING),
            (r"many.?proxy|Many.?Proxy", "Many proxies", "Simplify proxies", Severity.WARNING),
            (r"many.?decorator|Many.?Decorator", "Many decorators", "Simplify decorators", Severity.WARNING),
            (r"many.?adapter|Many.?Adapter", "Many adapters", "Simplify adapters", Severity.WARNING),
            (r"many.?bridge|Many.?Bridge", "Many bridges", "Simplify bridges", Severity.WARNING),
            (r"many.?composite|Many.?Composite", "Many composites", "Simplify composites", Severity.WARNING),
            (r"many.?flyweight|Many.?Flyweight", "Many flyweights", "Simplify flyweights", Severity.WARNING),
            (r"many.?chain|Many.?Chain", "Many chains", "Simplify chains", Severity.WARNING),
            (r"many.?command|Many.?Command", "Many commands", "Simplify commands", Severity.WARNING),
            (r"many.?iterator|Many.?Iterator", "Many iterators", "Simplify iterators", Severity.WARNING),
            (r"many.?mediator|Many.?Mediator", "Many mediators", "Simplify mediators", Severity.WARNING),
            (r"many.?memento|Many.?Memento", "Many mementos", "Simplify mementos", Severity.WARNING),
            (r"many.?observer|Many.?Observer", "Many observers", "Simplify observers", Severity.WARNING),
            (r"many.?state|Many.?State", "Many states", "Simplify states", Severity.WARNING),
            (r"many.?strategy|Many.?Strategy", "Many strategies", "Simplify strategies", Severity.WARNING),
            (r"many.?template|Many.?Template", "Many templates", "Simplify templates", Severity.WARNING),
            (r"many.?visitor|Many.?Visitor", "Many visitors", "Simplify visitors", Severity.WARNING),
        ]
        for line_num, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped.startswith('#') or stripped.startswith('//'):
                continue
            for pattern, message, severity in patterns:
                if re.search(pattern, line, re.IGNORECASE):
                    issues.append(self._create_issue(
                        file_path=file_path, line=line_num, message=message,
                        suggestion=message, severity=severity, code_snippet=stripped,
                    ))
        return issues
