"""
Comprehensive C/C++ specific rules.
"""
import re
from ..core.models import CodeIssue, Severity, IssueCategory
from ..core.rules import BaseRule


class C_CPP_ComprehensiveRules(BaseRule):
    @property
    def name(self) -> str:
        return "cpp_comprehensive"
    @property
    def description(self) -> str:
        return "C/C++ specific comprehensive rules"
    @property
    def category(self) -> IssueCategory:
        return IssueCategory.BEST_PRACTICE
    @property
    def severity(self) -> Severity:
        return Severity.INFO

    def check(self, file_path: str, content: str) -> list[CodeIssue]:
        if not file_path.endswith(('.c', '.cpp', '.cc', '.cxx', '.h', '.hpp')):
            return []
        issues = []
        lines = content.splitlines()
        patterns = [
            (r"#include\s*<", "System include", "Good: using system includes", Severity.INFO),
            (r"#include\s*\"", "Local include", "Good: using local includes", Severity.INFO),
            (r"#define\s+\w+", "Macro definition", "Good: using macros", Severity.INFO),
            (r"#ifdef\s+\w+", "Conditional compilation", "Good: using preprocessor", Severity.INFO),
            (r"#ifndef\s+\w+", "Include guard", "Good: using include guards", Severity.INFO),
            (r"#pragma\s+once", "Pragma once", "Good: include guard", Severity.INFO),
            (r"int\s+main\s*\(", "main function", "Good: main function", Severity.INFO),
            (r"void\s+\w+", "Void function", "Good: void functions", Severity.INFO),
            (r"int\s+\w+", "Int function", "Good: int functions", Severity.INFO),
            (r"char\s*\*", "C string", "Good: using C strings", Severity.INFO),
            (r"std::", "std namespace", "Good: using std namespace", Severity.INFO),
            (r"std::string", "std::string", "Good: using std::string", Severity.INFO),
            (r"std::vector", "std::vector", "Good: using std::vector", Severity.INFO),
            (r"std::map", "std::map", "Good: using std::map", Severity.INFO),
            (r"std::set", "std::set", "Good: using std::set", Severity.INFO),
            (r"std::unordered_map", "std::unordered_map", "Good: using unordered_map", Severity.INFO),
            (r"std::unordered_set", "std::unordered_set", "Good: using unordered_set", Severity.INFO),
            (r"std::list", "std::list", "Good: using std::list", Severity.INFO),
            (r"std::deque", "std::deque", "Good: using std::deque", Severity.INFO),
            (r"std::queue", "std::queue", "Good: using std::queue", Severity.INFO),
            (r"std::stack", "std::stack", "Good: using std::stack", Severity.INFO),
            (r"std::priority_queue", "std::priority_queue", "Good: using priority_queue", Severity.INFO),
            (r"std::array", "std::array", "Good: using std::array", Severity.INFO),
            (r"std::tuple", "std::tuple", "Good: using std::tuple", Severity.INFO),
            (r"std::pair", "std::pair", "Good: using std::pair", Severity.INFO),
            (r"std::optional", "std::optional", "Good: using std::optional", Severity.INFO),
            (r"std::variant", "std::variant", "Good: using std::variant", Severity.INFO),
            (r"std::any", "std::any", "Good: using std::any", Severity.INFO),
            (r"std::shared_ptr", "std::shared_ptr", "Good: using shared_ptr", Severity.INFO),
            (r"std::unique_ptr", "std::unique_ptr", "Good: using unique_ptr", Severity.INFO),
            (r"std::weak_ptr", "std::weak_ptr", "Good: using weak_ptr", Severity.INFO),
            (r"std::make_shared", "std::make_shared", "Good: using make_shared", Severity.INFO),
            (r"std::make_unique", "std::make_unique", "Good: using make_unique", Severity.INFO),
            (r"std::cin", "std::cin", "Good: using cin", Severity.INFO),
            (r"std::cout", "std::cout", "Good: using cout", Severity.INFO),
            (r"std::cerr", "std::cerr", "Good: using cerr", Severity.INFO),
            (r"std::endl", "std::endl", "Good: using endl", Severity.INFO),
            (r"printf\(", "printf()", "Good: using printf", Severity.INFO),
            (r"scanf\(", "scanf()", "Good: using scanf", Severity.INFO),
            (r"fprintf\(", "fprintf()", "Good: using fprintf", Severity.INFO),
            (r"sprintf\(", "sprintf()", "Use snprintf instead of sprintf", Severity.WARNING),
            (r"snprintf\(", "snprintf()", "Good: using snprintf", Severity.INFO),
            (r"sscanf\(", "sscanf()", "Good: using sscanf", Severity.INFO),
            (r"gets\(", "gets()", "Never use gets(); use fgets", Severity.CRITICAL),
            (r"fgets\(", "fgets()", "Good: using fgets", Severity.INFO),
            (r"strcpy\(", "strcpy()", "Use strncpy instead of strcpy", Severity.WARNING),
            (r"strncpy\(", "strncpy()", "Good: using strncpy", Severity.INFO),
            (r"strcat\(", "strcat()", "Use strncat instead of strcat", Severity.WARNING),
            (r"strncat\(", "strncat()", "Good: using strncat", Severity.INFO),
            (r"strlen\(", "strlen()", "Good: using strlen", Severity.INFO),
            (r"strcmp\(", "strcmp()", "Good: using strcmp", Severity.INFO),
            (r"strncmp\(", "strncmp()", "Good: using strncmp", Severity.INFO),
            (r"malloc\(", "malloc()", "Consider using new or smart pointers", Severity.INFO),
            (r"calloc\(", "calloc()", "Consider using new or smart pointers", Severity.INFO),
            (r"realloc\(", "realloc()", "Consider using vector", Severity.INFO),
            (r"free\(", "free()", "Consider using delete or smart pointers", Severity.INFO),
            (r"new\s+\w+", "new operator", "Good: using new", Severity.INFO),
            (r"delete\s+\w+", "delete operator", "Good: using delete", Severity.INFO),
            (r"new\s*\[\]", "new[]", "Good: array allocation", Severity.INFO),
            (r"delete\s*\[\]", "delete[]", "Good: array deallocation", Severity.INFO),
            (r"nullptr", "nullptr", "Good: using nullptr", Severity.INFO),
            (r"NULL", "NULL", "Use nullptr instead of NULL", Severity.INFO),
            (r"NULL", "NULL macro", "Prefer nullptr in C++", Severity.INFO),
            (r"typedef\s+", "typedef", "Use using instead of typedef", Severity.INFO),
            (r"using\s+\w+\s*=", "type alias", "Good: using type alias", Severity.INFO),
            (r"class\s+\w+", "class definition", "Good: defining classes", Severity.INFO),
            (r"struct\s+\w+", "struct definition", "Good: defining structs", Severity.INFO),
            (r"enum\s+\w+", "enum definition", "Good: defining enums", Severity.INFO),
            (r"enum\s+class", "enum class", "Good: scoped enums", Severity.INFO),
            (r"template\s*<", "template", "Good: using templates", Severity.INFO),
            (r"virtual\s+\w+", "virtual function", "Good: using virtual", Severity.INFO),
            (r"override\s*;", "override specifier", "Good: using override", Severity.INFO),
            (r"final\s*;", "final specifier", "Good: using final", Severity.INFO),
            (r"try\s*\{", "try block", "Good: error handling", Severity.INFO),
            (r"catch\s*\(", "catch block", "Good: catching exceptions", Severity.INFO),
            (r"throw\s+\w+", "throw statement", "Good: throwing exceptions", Severity.INFO),
            (r"noexcept", "noexcept", "Good: marking noexcept", Severity.INFO),
            (r"constexpr\s+\w+", "constexpr", "Good: using constexpr", Severity.INFO),
            (r"const\s+\w+", "const qualifier", "Good: using const", Severity.INFO),
            (r"static\s+\w+", "static qualifier", "Good: using static", Severity.INFO),
            (r"volatile\s+\w+", "volatile qualifier", "Consider using atomic", Severity.INFO),
            (r"mutable\s+\w+", "mutable qualifier", "Good: using mutable", Severity.INFO),
            (r"explicit\s+\w+", "explicit constructor", "Good: explicit constructors", Severity.INFO),
            (r"friend\s+\w+", "friend declaration", "Good: using friend", Severity.INFO),
            (r"namespace\s+\w+", "namespace", "Good: using namespaces", Severity.INFO),
            (r"using\s+namespace\s+std", "using namespace std", "Avoid using namespace std", Severity.WARNING),
            (r"auto\s+\w+", "auto keyword", "Good: using auto", Severity.INFO),
            (r"decltype\s*\(", "decltype", "Good: using decltype", Severity.INFO),
            (r"sizeof\s*\(", "sizeof", "Good: using sizeof", Severity.INFO),
            (r"static_cast<", "static_cast", "Good: using static_cast", Severity.INFO),
            (r"dynamic_cast<", "dynamic_cast", "Good: using dynamic_cast", Severity.INFO),
            (r"const_cast<", "const_cast", "Good: using const_cast", Severity.INFO),
            (r"reinterpret_cast<", "reinterpret_cast", "Avoid reinterpret_cast", Severity.INFO),
            (r"for\s*\(", "for loop", "Good: using for loops", Severity.INFO),
            (r"while\s*\(", "while loop", "Good: using while loops", Severity.INFO),
            (r"do\s*\{", "do-while loop", "Good: using do-while", Severity.INFO),
            (r"switch\s*\(", "switch statement", "Good: using switch", Severity.INFO),
            (r"case\s+\w+", "case label", "Good: using case", Severity.INFO),
            (r"default:", "default case", "Good: default case", Severity.INFO),
            (r"break;", "break statement", "Good: using break", Severity.INFO),
            (r"continue;", "continue statement", "Good: using continue", Severity.INFO),
            (r"return\s+\w+", "return statement", "Good: using return", Severity.INFO),
            (r"if\s*\(", "if statement", "Good: using if", Severity.INFO),
            (r"else\s+if", "else-if", "Good: using else-if", Severity.INFO),
            (r"else\s*\{", "else block", "Good: using else", Severity.INFO),
            (r"#include\s*<iostream>", "iostream", "Good: using iostream", Severity.INFO),
            (r"#include\s*<fstream>", "fstream", "Good: using fstream", Severity.INFO),
            (r"#include\s*<sstream>", "sstream", "Good: using sstream", Severity.INFO),
            (r"#include\s*<string>", "string header", "Good: using string", Severity.INFO),
            (r"#include\s*<vector>", "vector header", "Good: using vector", Severity.INFO),
            (r"#include\s*<map>", "map header", "Good: using map", Severity.INFO),
            (r"#include\s*<set>", "set header", "Good: using set", Severity.INFO),
            (r"#include\s*<algorithm>", "algorithm header", "Good: using algorithms", Severity.INFO),
            (r"#include\s*<memory>", "memory header", "Good: using smart pointers", Severity.INFO),
            (r"#include\s*<functional>", "functional header", "Good: using function objects", Severity.INFO),
            (r"#include\s*<thread>", "thread header", "Good: using threads", Severity.INFO),
            (r"#include\s*<mutex>", "mutex header", "Good: using mutexes", Severity.INFO),
            (r"#include\s*<atomic>", "atomic header", "Good: using atomics", Severity.INFO),
            (r"#include\s*<future>", "future header", "Good: using futures", Severity.INFO),
            (r"#include\s*<chrono>", "chrono header", "Good: using chrono", Severity.INFO),
            (r"#include\s*<filesystem>", "filesystem header", "Good: using filesystem", Severity.INFO),
            (r"#include\s*<numeric>", "numeric header", "Good: using numeric algorithms", Severity.INFO),
            (r"#include\s*<limits>", "limits header", "Good: using limits", Severity.INFO),
            (r"#include\s*<type_traits>", "type_traits header", "Good: using type traits", Severity.INFO),
            (r"std::begin\(", "std::begin()", "Good: using std::begin", Severity.INFO),
            (r"std::end\(", "std::end()", "Good: using std::end", Severity.INFO),
            (r"std::move\(", "std::move()", "Good: using std::move", Severity.INFO),
            (r"std::forward\(", "std::forward()", "Good: using std::forward", Severity.INFO),
            (r"std::swap\(", "std::swap()", "Good: using std::swap", Severity.INFO),
            (r"std::min\(", "std::min()", "Good: using std::min", Severity.INFO),
            (r"std::max\(", "std::max()", "Good: using std::max", Severity.INFO),
            (r"std::abs\(", "std::abs()", "Good: using std::abs", Severity.INFO),
            (r"std::sort\(", "std::sort()", "Good: using std::sort", Severity.INFO),
            (r"std::stable_sort\(", "std::stable_sort()", "Good: using std::stable_sort", Severity.INFO),
            (r"std::partial_sort\(", "std::partial_sort()", "Good: using std::partial_sort", Severity.INFO),
            (r"std::nth_element\(", "std::nth_element()", "Good: using std::nth_element", Severity.INFO),
            (r"std::binary_search\(", "std::binary_search()", "Good: using binary search", Severity.INFO),
            (r"std::lower_bound\(", "std::lower_bound()", "Good: using lower_bound", Severity.INFO),
            (r"std::upper_bound\(", "std::upper_bound()", "Good: using upper_bound", Severity.INFO),
            (r"std::equal_range\(", "std::equal_range()", "Good: using equal_range", Severity.INFO),
            (r"std::find\(", "std::find()", "Good: using std::find", Severity.INFO),
            (r"std::find_if\(", "std::find_if()", "Good: using std::find_if", Severity.INFO),
            (r"std::count\(", "std::count()", "Good: using std::count", Severity.INFO),
            (r"std::count_if\(", "std::count_if()", "Good: using std::count_if", Severity.INFO),
            (r"std::transform\(", "std::transform()", "Good: using std::transform", Severity.INFO),
            (r"std::for_each\(", "std::for_each()", "Good: using std::for_each", Severity.INFO),
            (r"std::copy\(", "std::copy()", "Good: using std::copy", Severity.INFO),
            (r"std::fill\(", "std::fill()", "Good: using std::fill", Severity.INFO),
            (r"std::generate\(", "std::generate()", "Good: using std::generate", Severity.INFO),
            (r"std::remove\(", "std::remove()", "Good: using std::remove", Severity.INFO),
            (r"std::unique\(", "std::unique()", "Good: using std::unique", Severity.INFO),
            (r"std::reverse\(", "std::reverse()", "Good: using std::reverse", Severity.INFO),
            (r"std::rotate\(", "std::rotate()", "Good: using std::rotate", Severity.INFO),
            (r"std::shuffle\(", "std::shuffle()", "Good: using std::shuffle", Severity.INFO),
            (r"std::sample\(", "std::sample()", "Good: using std::sample", Severity.INFO),
            (r"std::accumulate\(", "std::accumulate()", "Good: using std::accumulate", Severity.INFO),
            (r"std::inner_product\(", "std::inner_product()", "Good: using std::inner_product", Severity.INFO),
            (r"std::adjacent_difference\(", "std::adjacent_difference()", "Good: using adjacent_difference", Severity.INFO),
            (r"std::partial_sum\(", "std::partial_sum()", "Good: using partial_sum", Severity.INFO),
            (r"std::iota\(", "std::iota()", "Good: using std::iota", Severity.INFO),
            (r"std::gcd\(", "std::gcd()", "Good: using std::gcd", Severity.INFO),
            (r"std::lcm\(", "std::lcm()", "Good: using std::lcm", Severity.INFO),
            (r"std::midpoint\(", "std::midpoint()", "Good: using std::midpoint", Severity.INFO),
            (r"std::clamp\(", "std::clamp()", "Good: using std::clamp", Severity.INFO),
            (r"std::invoke\(", "std::invoke()", "Good: using std::invoke", Severity.INFO),
            (r"std::apply\(", "std::apply()", "Good: using std::apply", Severity.INFO),
            (r"std::make_from_tuple\(", "std::make_from_tuple()", "Good: using make_from_tuple", Severity.INFO),
            (r"std::visit\(", "std::visit()", "Good: using std::visit", Severity.INFO),
            (r"std::holds_alternative\(", "std::holds_alternative()", "Good: using holds_alternative", Severity.INFO),
            (r"std::get<", "std::get<>()", "Good: using std::get", Severity.INFO),
            (r"std::get_if\(", "std::get_if()", "Good: using std::get_if", Severity.INFO),
            (r"std::make_tuple\(", "std::make_tuple()", "Good: using make_tuple", Severity.INFO),
            (r"std::make_pair\(", "std::make_pair()", "Good: using make_pair", Severity.INFO),
            (r"std::tie\(", "std::tie()", "Good: using std::tie", Severity.INFO),
            (r"std::forward_as_tuple\(", "std::forward_as_tuple()", "Good: using forward_as_tuple", Severity.INFO),
            (r"std::tuple_cat\(", "std::tuple_cat()", "Good: using tuple_cat", Severity.INFO),
            (r"std::piecewise_construct", "piecewise_construct", "Good: using piecewise_construct", Severity.INFO),
            (r"std::inserter\(", "std::inserter()", "Good: using std::inserter", Severity.INFO),
            (r"std::back_inserter\(", "std::back_inserter()", "Good: using back_inserter", Severity.INFO),
            (r"std::front_inserter\(", "std::front_inserter()", "Good: using front_inserter", Severity.INFO),
            (r"std::ostream_iterator", "ostream_iterator", "Good: using ostream_iterator", Severity.INFO),
            (r"std::istream_iterator", "istream_iterator", "Good: using istream_iterator", Severity.INFO),
            (r"std::move_iterator", "move_iterator", "Good: using move_iterator", Severity.INFO),
            (r"std::reverse_iterator", "reverse_iterator", "Good: using reverse_iterator", Severity.INFO),
            (r"std::iterator_traits", "iterator_traits", "Good: using iterator_traits", Severity.INFO),
            (r"std::distance\(", "std::distance()", "Good: using std::distance", Severity.INFO),
            (r"std::advance\(", "std::advance()", "Good: using std::advance", Severity.INFO),
            (r"std::next\(", "std::next()", "Good: using std::next", Severity.INFO),
            (r"std::prev\(", "std::prev()", "Good: using std::prev", Severity.INFO),
            (r"std::make_heap\(", "std::make_heap()", "Good: using make_heap", Severity.INFO),
            (r"std::push_heap\(", "std::push_heap()", "Good: using push_heap", Severity.INFO),
            (r"std::pop_heap\(", "std::pop_heap()", "Good: using pop_heap", Severity.INFO),
            (r"std::sort_heap\(", "std::sort_heap()", "Good: using sort_heap", Severity.INFO),
            (r"std::is_heap\(", "std::is_heap()", "Good: using is_heap", Severity.INFO),
            (r"std::is_sorted\(", "std::is_sorted()", "Good: using is_sorted", Severity.INFO),
            (r"std::is_partitioned\(", "std::is_partitioned()", "Good: using is_partitioned", Severity.INFO),
            (r"std::partition\(", "std::partition()", "Good: using partition", Severity.INFO),
            (r"std::stable_partition\(", "std::stable_partition()", "Good: using stable_partition", Severity.INFO),
            (r"std::partition_copy\(", "std::partition_copy()", "Good: using partition_copy", Severity.INFO),
            (r"std::partition_point\(", "std::partition_point()", "Good: using partition_point", Severity.INFO),
            (r"std::is_permutation\(", "std::is_permutation()", "Good: using is_permutation", Severity.INFO),
            (r"std::next_permutation\(", "std::next_permutation()", "Good: using next_permutation", Severity.INFO),
            (r"std::prev_permutation\(", "std::prev_permutation()", "Good: using prev_permutation", Severity.INFO),
            (r"std::set_intersection\(", "std::set_intersection()", "Good: using set_intersection", Severity.INFO),
            (r"std::set_union\(", "std::set_union()", "Good: using set_union", Severity.INFO),
            (r"std::set_difference\(", "std::set_difference()", "Good: using set_difference", Severity.INFO),
            (r"std::set_symmetric_difference\(", "std::set_symmetric_difference()", "Good: using set_symmetric_difference", Severity.INFO),
            (r"std::includes\(", "std::includes()", "Good: using includes", Severity.INFO),
            (r"std::set_merge\(", "std::set_merge()", "Good: using set_merge", Severity.INFO),
            (r"std::set_merge_unique\(", "std::set_merge_unique()", "Good: using merge_unique", Severity.INFO),
            (r"std::lexicographical_compare\(", "std::lexicographical_compare()", "Good: using lexicographical_compare", Severity.INFO),
            (r"std::equal\(", "std::equal()", "Good: using std::equal", Severity.INFO),
            (r"std::mismatch\(", "std::mismatch()", "Good: using std::mismatch", Severity.INFO),
            (r"std::swap_ranges\(", "std::swap_ranges()", "Good: using swap_ranges", Severity.INFO),
            (r"std::uninitialized_copy\(", "std::uninitialized_copy()", "Good: using uninitialized_copy", Severity.INFO),
            (r"std::uninitialized_fill\(", "std::uninitialized_fill()", "Good: using uninitialized_fill", Severity.INFO),
            (r"std::uninitialized_move\(", "std::uninitialized_move()", "Good: using uninitialized_move", Severity.INFO),
            (r"std::uninitialized_default_construct\(", "std::uninitialized_default_construct()", "Good: using uninitialized_default_construct", Severity.INFO),
            (r"std::uninitialized_value_construct\(", "std::uninitialized_value_construct()", "Good: using uninitialized_value_construct", Severity.INFO),
            (r"std::destroy\(", "std::destroy()", "Good: using std::destroy", Severity.INFO),
            (r"std::destroy_n\(", "std::destroy_n()", "Good: using destroy_n", Severity.INFO),
            (r"std::destroy_at\(", "std::destroy_at()", "Good: using destroy_at", Severity.INFO),
            (r"std::construct_at\(", "std::construct_at()", "Good: using construct_at", Severity.INFO),
            (r"std::ranges::", "std::ranges::", "Good: using ranges", Severity.INFO),
            (r"std::views::", "std::views::", "Good: using views", Severity.INFO),
            (r"std::format\(", "std::format()", "Good: using std::format", Severity.INFO),
            (r"std::print\(", "std::print()", "Good: using std::print", Severity.INFO),
            (r"std::println\(", "std::println()", "Good: using std::println", Severity.INFO),
            (r"std::span<", "std::span", "Good: using std::span", Severity.INFO),
            (r"std::source_location", "std::source_location", "Good: using source_location", Severity.INFO),
            (r"std::expected", "std::expected", "Good: using expected", Severity.INFO),
            (r"std::generator", "std::generator", "Good: using generator", Severity.INFO),
            (r"std::simd", "std::simd", "Good: using SIMD", Severity.INFO),
            (r"std::jthread", "std::jthread", "Good: using jthread", Severity.INFO),
            (r"std::stop_token", "std::stop_token", "Good: using stop_token", Severity.INFO),
            (r"std::latch", "std::latch", "Good: using latch", Severity.INFO),
            (r"std::barrier", "std::barrier", "Good: using barrier", Severity.INFO),
            (r"std::counting_semaphore", "std::counting_semaphore", "Good: using semaphore", Severity.INFO),
            (r"std::binary_semaphore", "std::binary_semaphore", "Good: using binary_semaphore", Severity.INFO),
            (r"std::atomic_ref", "std::atomic_ref", "Good: using atomic_ref", Severity.INFO),
            (r"std::atomic_signal_fence", "std::atomic_signal_fence", "Good: using atomic_signal_fence", Severity.INFO),
            (r"std::atomic_thread_fence", "std::atomic_thread_fence", "Good: using atomic_thread_fence", Severity.INFO),
            (r"std::memory_order", "std::memory_order", "Good: using memory_order", Severity.INFO),
            (r"std::kill_dependency\(", "std::kill_dependency()", "Good: using kill_dependency", Severity.INFO),
            (r"std::apply\(", "std::apply()", "Good: using std::apply", Severity.INFO),
            (r"std::make_from_tuple\(", "std::make_from_tuple()", "Good: using make_from_tuple", Severity.INFO),
            (r"std::forward_as_tuple\(", "std::forward_as_tuple()", "Good: using forward_as_tuple", Severity.INFO),
            (r"std::tuple_cat\(", "std::tuple_cat()", "Good: using tuple_cat", Severity.INFO),
            (r"std::tuple_size", "std::tuple_size", "Good: using tuple_size", Severity.INFO),
            (r"std::tuple_element", "std::tuple_element", "Good: using tuple_element", Severity.INFO),
            (r"std::get<", "std::get<>()", "Good: using std::get", Severity.INFO),
            (r"std::get_if\(", "std::get_if()", "Good: using std::get_if", Severity.INFO),
            (r"std::visit\(", "std::visit()", "Good: using std::visit", Severity.INFO),
            (r"std::holds_alternative\(", "std::holds_alternative()", "Good: using holds_alternative", Severity.INFO),
            (r"std::monostate", "std::monostate", "Good: using monostate", Severity.INFO),
            (r"std::bad_variant_access", "std::bad_variant_access", "Good: catching bad_variant_access", Severity.INFO),
            (r"std::get_if\(", "std::get_if()", "Good: using std::get_if", Severity.INFO),
            (r"std::make_tuple\(", "std::make_tuple()", "Good: using make_tuple", Severity.INFO),
            (r"std::make_pair\(", "std::make_pair()", "Good: using make_pair", Severity.INFO),
            (r"std::tie\(", "std::tie()", "Good: using std::tie", Severity.INFO),
            (r"std::forward_as_tuple\(", "std::forward_as_tuple()", "Good: using forward_as_tuple", Severity.INFO),
            (r"std::tuple_cat\(", "std::tuple_cat()", "Good: using tuple_cat", Severity.INFO),
            (r"std::piecewise_construct", "piecewise_construct", "Good: using piecewise_construct", Severity.INFO),
            (r"std::inserter\(", "std::inserter()", "Good: using std::inserter", Severity.INFO),
            (r"std::back_inserter\(", "std::back_inserter()", "Good: using back_inserter", Severity.INFO),
            (r"std::front_inserter\(", "std::front_inserter()", "Good: using front_inserter", Severity.INFO),
        ]
        for line_num, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped.startswith('//') or stripped.startswith('/*'):
                continue
            for pattern, message, severity in patterns:
                if re.search(pattern, line):
                    issues.append(self._create_issue(
                        file_path=file_path, line=line_num, message=message,
                        suggestion=message, severity=severity, code_snippet=stripped,
                    ))
        return issues
