"""
Comprehensive database patterns for SQL, NoSQL, and ORM.
"""
import re
from ..core.models import CodeIssue, Severity, IssueCategory
from ..core.rules import BaseRule


class DatabaseComprehensiveRules(BaseRule):
    @property
    def name(self) -> str:
        return "database_comprehensive"
    @property
    def description(self) -> str:
        return "Comprehensive database patterns"
    @property
    def category(self) -> IssueCategory:
        return IssueCategory.BEST_PRACTICE
    @property
    def severity(self) -> Severity:
        return Severity.INFO

    def check(self, file_path: str, content: str) -> list[CodeIssue]:
        issues = []
        lines = content.splitlines()
        patterns = [
            # SQL keywords
            (r"SELECT\s+", "SELECT statement", "Good: querying data", Severity.INFO),
            (r"INSERT\s+INTO", "INSERT statement", "Good: inserting data", Severity.INFO),
            (r"UPDATE\s+\w+\s+SET", "UPDATE statement", "Good: updating data", Severity.INFO),
            (r"DELETE\s+FROM", "DELETE statement", "Good: deleting data", Severity.INFO),
            (r"CREATE\s+TABLE", "CREATE TABLE", "Good: creating tables", Severity.INFO),
            (r"ALTER\s+TABLE", "ALTER TABLE", "Good: altering tables", Severity.INFO),
            (r"DROP\s+TABLE", "DROP TABLE", "Good: dropping tables", Severity.INFO),
            (r"CREATE\s+INDEX", "CREATE INDEX", "Good: creating indexes", Severity.INFO),
            (r"DROP\s+INDEX", "DROP INDEX", "Good: dropping indexes", Severity.INFO),
            (r"CREATE\s+VIEW", "CREATE VIEW", "Good: creating views", Severity.INFO),
            (r"CREATE\s+PROCEDURE", "CREATE PROCEDURE", "Good: creating procedures", Severity.INFO),
            (r"CREATE\s+FUNCTION", "CREATE FUNCTION", "Good: creating functions", Severity.INFO),
            (r"CREATE\s+TRIGGER", "CREATE TRIGGER", "Good: creating triggers", Severity.INFO),
            (r"CREATE\s+EVENT", "CREATE EVENT", "Good: creating events", Severity.INFO),
            (r"GRANT\s+", "GRANT statement", "Good: granting permissions", Severity.INFO),
            (r"REVOKE\s+", "REVOKE statement", "Good: revoking permissions", Severity.INFO),
            # SQL joins
            (r"INNER\s+JOIN", "INNER JOIN", "Good: inner join", Severity.INFO),
            (r"LEFT\s+JOIN", "LEFT JOIN", "Good: left join", Severity.INFO),
            (r"RIGHT\s+JOIN", "RIGHT JOIN", "Good: right join", Severity.INFO),
            (r"FULL\s+JOIN", "FULL JOIN", "Good: full join", Severity.INFO),
            (r"CROSS\s+JOIN", "CROSS JOIN", "Good: cross join", Severity.INFO),
            (r"LEFT\s+OUTER\s+JOIN", "LEFT OUTER JOIN", "Good: left outer join", Severity.INFO),
            (r"RIGHT\s+OUTER\s+JOIN", "RIGHT OUTER JOIN", "Good: right outer join", Severity.INFO),
            (r"FULL\s+OUTER\s+JOIN", "FULL OUTER JOIN", "Good: full outer join", Severity.INFO),
            (r"JOIN\s+\w+\s+ON", "JOIN ON", "Good: joining with condition", Severity.INFO),
            # SQL conditions
            (r"WHERE\s+", "WHERE clause", "Good: filtering data", Severity.INFO),
            (r"AND\s+", "AND condition", "Good: combining conditions", Severity.INFO),
            (r"OR\s+", "OR condition", "Good: alternative conditions", Severity.INFO),
            (r"NOT\s+", "NOT condition", "Good: negating conditions", Severity.INFO),
            (r"IN\s*\(", "IN clause", "Good: checking membership", Severity.INFO),
            (r"BETWEEN\s+", "BETWEEN clause", "Good: range check", Severity.INFO),
            (r"LIKE\s+", "LIKE clause", "Good: pattern matching", Severity.INFO),
            (r"IS\s+NULL", "IS NULL", "Good: null check", Severity.INFO),
            (r"IS\s+NOT\s+NULL", "IS NOT NULL", "Good: non-null check", Severity.INFO),
            (r"EXISTS\s*\(", "EXISTS clause", "Good: existence check", Severity.INFO),
            (r"ANY\s*\(", "ANY clause", "Good: any comparison", Severity.INFO),
            (r"ALL\s*\(", "ALL clause", "Good: all comparison", Severity.INFO),
            (r"SOME\s*\(", "SOME clause", "Good: some comparison", Severity.INFO),
            # SQL aggregations
            (r"GROUP\s+BY", "GROUP BY", "Good: grouping data", Severity.INFO),
            (r"HAVING\s+", "HAVING clause", "Good: filtering groups", Severity.INFO),
            (r"ORDER\s+BY", "ORDER BY", "Good: sorting data", Severity.INFO),
            (r"ASC\b", "ASC order", "Good: ascending order", Severity.INFO),
            (r"DESC\b", "DESC order", "Good: descending order", Severity.INFO),
            (r"LIMIT\s+", "LIMIT clause", "Good: limiting results", Severity.INFO),
            (r"OFFSET\s+", "OFFSET clause", "Good: offsetting results", Severity.INFO),
            (r"FETCH\s+FIRST", "FETCH FIRST", "Good: SQL standard limit", Severity.INFO),
            (r"TOP\s+\d+", "TOP clause", "Good: SQL Server limit", Severity.INFO),
            (r"UNION\s+ALL", "UNION ALL", "Good: combining results", Severity.INFO),
            (r"UNION\s+(?!ALL)", "UNION", "Good: combining distinct results", Severity.INFO),
            (r"INTERSECT", "INTERSECT", "Good: intersection", Severity.INFO),
            (r"EXCEPT", "EXCEPT", "Good: difference", Severity.INFO),
            (r"DISTINCT\s+", "DISTINCT", "Good: removing duplicates", Severity.INFO),
            # SQL functions
            (r"COUNT\s*\(", "COUNT function", "Good: counting rows", Severity.INFO),
            (r"SUM\s*\(", "SUM function", "Good: summing values", Severity.INFO),
            (r"AVG\s*\(", "AVG function", "Good: averaging values", Severity.INFO),
            (r"MIN\s*\(", "MIN function", "Good: minimum value", Severity.INFO),
            (r"MAX\s*\(", "MAX function", "Good: maximum value", Severity.INFO),
            (r"COALESCE\s*\(", "COALESCE function", "Good: handling nulls", Severity.INFO),
            (r"NULLIF\s*\(", "NULLIF function", "Good: null handling", Severity.INFO),
            (r"IFNULL\s*\(", "IFNULL function", "Good: MySQL null handling", Severity.INFO),
            (r"IF\s*\(", "IF function", "Good: conditional logic", Severity.INFO),
            (r"CASE\s+WHEN", "CASE expression", "Good: conditional logic", Severity.INFO),
            (r"WHEN\s+\w+\s+THEN", "WHEN clause", "Good: case when", Severity.INFO),
            (r"ELSE\s+", "ELSE clause", "Good: case else", Severity.INFO),
            (r"END\s*;", "END clause", "Good: case end", Severity.INFO),
            (r"CAST\s*\(", "CAST function", "Good: type casting", Severity.INFO),
            (r"CONVERT\s*\(", "CONVERT function", "Good: type conversion", Severity.INFO),
            (r"ROUND\s*\(", "ROUND function", "Good: rounding values", Severity.INFO),
            (r"FLOOR\s*\(", "FLOOR function", "Good: flooring values", Severity.INFO),
            (r"CEIL\s*\(", "CEIL function", "Good: ceiling values", Severity.INFO),
            (r"ABS\s*\(", "ABS function", "Good: absolute value", Severity.INFO),
            (r"MOD\s*\(", "MOD function", "Good: modulo", Severity.INFO),
            (r"POWER\s*\(", "POWER function", "Good: power", Severity.INFO),
            (r"SQRT\s*\(", "SQRT function", "Good: square root", Severity.INFO),
            (r"LOG\s*\(", "LOG function", "Good: logarithm", Severity.INFO),
            (r"EXP\s*\(", "EXP function", "Good: exponential", Severity.INFO),
            (r"LN\s*\(", "LN function", "Good: natural log", Severity.INFO),
            (r"SIGN\s*\(", "SIGN function", "Good: sign function", Severity.INFO),
            # SQL date functions
            (r"NOW\s*\(", "NOW function", "Good: current timestamp", Severity.INFO),
            (r"CURDATE\s*\(", "CURDATE function", "Good: current date", Severity.INFO),
            (r"CURTIME\s*\(", "CURTIME function", "Good: current time", Severity.INFO),
            (r"DATE\s*\(", "DATE function", "Good: date extraction", Severity.INFO),
            (r"TIME\s*\(", "TIME function", "Good: time extraction", Severity.INFO),
            (r"DATETIME\s*\(", "DATETIME function", "Good: datetime", Severity.INFO),
            (r"YEAR\s*\(", "YEAR function", "Good: year extraction", Severity.INFO),
            (r"MONTH\s*\(", "MONTH function", "Good: month extraction", Severity.INFO),
            (r"DAY\s*\(", "DAY function", "Good: day extraction", Severity.INFO),
            (r"HOUR\s*\(", "HOUR function", "Good: hour extraction", Severity.INFO),
            (r"MINUTE\s*\(", "MINUTE function", "Good: minute extraction", Severity.INFO),
            (r"SECOND\s*\(", "SECOND function", "Good: second extraction", Severity.INFO),
            (r"DATEDIFF\s*\(", "DATEDIFF function", "Good: date difference", Severity.INFO),
            (r"DATE_ADD\s*\(", "DATE_ADD function", "Good: adding dates", Severity.INFO),
            (r"DATE_SUB\s*\(", "DATE_SUB function", "Good: subtracting dates", Severity.INFO),
            (r"DATE_FORMAT\s*\(", "DATE_FORMAT function", "Good: formatting dates", Severity.INFO),
            (r"STR_TO_DATE\s*\(", "STR_TO_DATE function", "Good: parsing dates", Severity.INFO),
            (r"EXTRACT\s*\(", "EXTRACT function", "Good: extracting date parts", Severity.INFO),
            (r"UNIX_TIMESTAMP\s*\(", "UNIX_TIMESTAMP function", "Good: unix timestamp", Severity.INFO),
            (r"FROM_UNIXTIME\s*\(", "FROM_UNIXTIME function", "Good: from unix timestamp", Severity.INFO),
            (r"TIME_TO_SEC\s*\(", "TIME_TO_SEC function", "Good: time to seconds", Severity.INFO),
            (r"SEC_TO_TIME\s*\(", "SEC_TO_TIME function", "Good: seconds to time", Severity.INFO),
            (r"TIME_FORMAT\s*\(", "TIME_FORMAT function", "Good: time formatting", Severity.INFO),
            (r"TIMEDIFF\s*\(", "TIMEDIFF function", "Good: time difference", Severity.INFO),
            (r"ADDTIME\s*\(", "ADDTIME function", "Good: adding time", Severity.INFO),
            (r"SUBTIME\s*\(", "SUBTIME function", "Good: subtracting time", Severity.INFO),
            (r"MAKETIME\s*\(", "MAKETIME function", "Good: making time", Severity.INFO),
            # SQL string functions
            (r"FORMAT\s*\(", "FORMAT function", "Good: formatting", Severity.INFO),
            (r"CONCAT\s*\(", "CONCAT function", "Good: concatenation", Severity.INFO),
            (r"CONCAT_WS\s*\(", "CONCAT_WS function", "Good: concatenation with separator", Severity.INFO),
            (r"SUBSTRING\s*\(", "SUBSTRING function", "Good: substring", Severity.INFO),
            (r"SUBSTR\s*\(", "SUBSTR function", "Good: substring", Severity.INFO),
            (r"LEFT\s*\(", "LEFT function", "Good: left substring", Severity.INFO),
            (r"RIGHT\s*\(", "RIGHT function", "Good: right substring", Severity.INFO),
            (r"UPPER\s*\(", "UPPER function", "Good: uppercase", Severity.INFO),
            (r"LOWER\s*\(", "LOWER function", "Good: lowercase", Severity.INFO),
            (r"TRIM\s*\(", "TRIM function", "Good: trimming", Severity.INFO),
            (r"LTRIM\s*\(", "LTRIM function", "Good: left trim", Severity.INFO),
            (r"RTRIM\s*\(", "RTRIM function", "Good: right trim", Severity.INFO),
            (r"LENGTH\s*\(", "LENGTH function", "Good: string length", Severity.INFO),
            (r"CHAR_LENGTH\s*\(", "CHAR_LENGTH function", "Good: character length", Severity.INFO),
            (r"LOCATE\s*\(", "LOCATE function", "Good: locating substring", Severity.INFO),
            (r"INSTR\s*\(", "INSTR function", "Good: finding substring", Severity.INFO),
            (r"REVERSE\s*\(", "REVERSE function", "Good: reversing string", Severity.INFO),
            (r"REPEAT\s*\(", "REPEAT function", "Good: repeating string", Severity.INFO),
            (r"SPACE\s*\(", "SPACE function", "Good: creating spaces", Severity.INFO),
            (r"LPAD\s*\(", "LPAD function", "Good: left padding", Severity.INFO),
            (r"RPAD\s*\(", "RPAD function", "Good: right padding", Severity.INFO),
            (r"ELT\s*\(", "ELT function", "Good: element selection", Severity.INFO),
            (r"FIELD\s*\(", "FIELD function", "Good: field position", Severity.INFO),
            (r"FIND_IN_SET\s*\(", "FIND_IN_SET function", "Good: finding in set", Severity.INFO),
            (r"ASCII\s*\(", "ASCII function", "Good: ASCII value", Severity.INFO),
            (r"CHAR\s*\(", "CHAR function", "Good: character from ASCII", Severity.INFO),
            (r"CONV\s*\(", "CONV function", "Good: number conversion", Severity.INFO),
            (r"BIN\s*\(", "BIN function", "Good: binary representation", Severity.INFO),
            (r"OCT\s*\(", "OCT function", "Good: octal representation", Severity.INFO),
            (r"HEX\s*\(", "HEX function", "Good: hex representation", Severity.INFO),
            (r"LCASE\s*\(", "LCASE function", "Good: lowercase", Severity.INFO),
            (r"UCASE\s*\(", "UCASE function", "Good: uppercase", Severity.INFO),
            (r"INITCAP\s*\(", "INITCAP function", "Good: initial caps", Severity.INFO),
            (r"SOUNDEX\s*\(", "SOUNDEX function", "Good: soundex", Severity.INFO),
            (r"SPEACHES\s*\(", "SPEACHES function", "Good: soundex", Severity.INFO),
            # SQL transaction control
            (r"BEGIN\s+TRANSACTION", "BEGIN TRANSACTION", "Good: starting transaction", Severity.INFO),
            (r"BEGIN\s+TRAN", "BEGIN TRAN", "Good: starting transaction", Severity.INFO),
            (r"COMMIT", "COMMIT", "Good: committing transaction", Severity.INFO),
            (r"ROLLBACK", "ROLLBACK", "Good: rolling back transaction", Severity.INFO),
            (r"SAVEPOINT\s+", "SAVEPOINT", "Good: creating savepoint", Severity.INFO),
            (r"RELEASE\s+SAVEPOINT", "RELEASE SAVEPOINT", "Good: releasing savepoint", Severity.INFO),
            (r"START\s+TRANSACTION", "START TRANSACTION", "Good: starting transaction", Severity.INFO),
            # SQL data types
            (r"VARCHAR\s*\(", "VARCHAR type", "Good: variable character", Severity.INFO),
            (r"CHAR\s*\(", "CHAR type", "Good: fixed character", Severity.INFO),
            (r"TEXT", "TEXT type", "Good: text type", Severity.INFO),
            (r"BLOB", "BLOB type", "Good: binary large object", Severity.INFO),
            (r"CLOB", "CLOB type", "Good: character large object", Severity.INFO),
            (r"NCHAR\s*\(", "NCHAR type", "Good: national character", Severity.INFO),
            (r"NVARCHAR\s*\(", "NVARCHAR type", "Good: national variable char", Severity.INFO),
            (r"BINARY\s*\(", "BINARY type", "Good: binary type", Severity.INFO),
            (r"VARBINARY\s*\(", "VARBINARY type", "Good: variable binary", Severity.INFO),
            (r"BOOLEAN", "BOOLEAN type", "Good: boolean type", Severity.INFO),
            (r"BIT", "BIT type", "Good: bit type", Severity.INFO),
            (r"TINYINT", "TINYINT type", "Good: tiny integer", Severity.INFO),
            (r"SMALLINT", "SMALLINT type", "Good: small integer", Severity.INFO),
            (r"INT\s*\(", "INT type", "Good: integer", Severity.INFO),
            (r"INTEGER", "INTEGER type", "Good: integer", Severity.INFO),
            (r"BIGINT", "BIGINT type", "Good: big integer", Severity.INFO),
            (r"FLOAT\s*\(", "FLOAT type", "Good: float", Severity.INFO),
            (r"DOUBLE\s*\(", "DOUBLE type", "Good: double", Severity.INFO),
            (r"DECIMAL\s*\(", "DECIMAL type", "Good: decimal", Severity.INFO),
            (r"NUMERIC\s*\(", "NUMERIC type", "Good: numeric", Severity.INFO),
            (r"DATE\b", "DATE type", "Good: date type", Severity.INFO),
            (r"TIME\b", "TIME type", "Good: time type", Severity.INFO),
            (r"DATETIME", "DATETIME type", "Good: datetime type", Severity.INFO),
            (r"TIMESTAMP", "TIMESTAMP type", "Good: timestamp type", Severity.INFO),
            (r"INTERVAL\s+", "INTERVAL type", "Good: interval type", Severity.INFO),
            (r"JSON\b", "JSON type", "Good: JSON type", Severity.INFO),
            (r"JSONB", "JSONB type", "Good: binary JSON", Severity.INFO),
            (r"XML\b", "XML type", "Good: XML type", Severity.INFO),
            (r"UUID", "UUID type", "Good: UUID type", Severity.INFO),
            (r"ARRAY\s*\(", "ARRAY type", "Good: array type", Severity.INFO),
            (r"ENUM\s*\(", "ENUM type", "Good: enum type", Severity.INFO),
            (r"SET\s*\(", "SET type", "Good: set type", Severity.INFO),
            (r"GEOMETRY", "GEOMETRY type", "Good: geometry type", Severity.INFO),
            (r"POINT", "POINT type", "Good: point type", Severity.INFO),
            (r"LINESTRING", "LINESTRING type", "Good: linestring type", Severity.INFO),
            (r"POLYGON", "POLYGON type", "Good: polygon type", Severity.INFO),
            (r"MULTIPOINT", "MULTIPOINT type", "Good: multipoint type", Severity.INFO),
            (r"MULTILINESTRING", "MULTILINESTRING type", "Good: multilinestring type", Severity.INFO),
            (r"MULTIPOLYGON", "MULTIPOLYGON type", "Good: multipolygon type", Severity.INFO),
            (r"GEOMETRYCOLLECTION", "GEOMETRYCOLLECTION type", "Good: geometry collection", Severity.INFO),
            # SQL schema
            (r"AUTO_INCREMENT", "AUTO_INCREMENT", "Good: auto increment", Severity.INFO),
            (r"SERIAL", "SERIAL type", "Good: serial type", Severity.INFO),
            (r"IDENTITY\s*\(", "IDENTITY", "Good: identity column", Severity.INFO),
            (r"DEFAULT\s+", "DEFAULT constraint", "Good: default value", Severity.INFO),
            (r"NOT\s+NULL", "NOT NULL constraint", "Good: not null", Severity.INFO),
            (r"PRIMARY\s+KEY", "PRIMARY KEY", "Good: primary key", Severity.INFO),
            (r"FOREIGN\s+KEY", "FOREIGN KEY", "Good: foreign key", Severity.INFO),
            (r"UNIQUE\s*\(", "UNIQUE constraint", "Good: unique constraint", Severity.INFO),
            (r"CHECK\s*\(", "CHECK constraint", "Good: check constraint", Severity.INFO),
            (r"INDEX\s+\w+", "INDEX", "Good: creating index", Severity.INFO),
            (r"CONSTRAINT\s+\w+", "CONSTRAINT", "Good: naming constraint", Severity.INFO),
            (r"REFERENCES\s+\w+", "REFERENCES", "Good: foreign key reference", Severity.INFO),
            (r"ON\s+DELETE\s+", "ON DELETE", "Good: delete cascade", Severity.INFO),
            (r"ON\s+UPDATE\s+", "ON UPDATE", "Good: update cascade", Severity.INFO),
            (r"CASCADE", "CASCADE", "Good: cascade", Severity.INFO),
            (r"SET\s+NULL", "SET NULL", "Good: set null", Severity.INFO),
            (r"SET\s+DEFAULT", "SET DEFAULT", "Good: set default", Severity.INFO),
            (r"RESTRICT", "RESTRICT", "Good: restrict", Severity.INFO),
            (r"NO\s+ACTION", "NO ACTION", "Good: no action", Severity.INFO),
            # SQL admin
            (r"EXPLAIN\s+", "EXPLAIN", "Good: explaining queries", Severity.INFO),
            (r"ANALYZE\s+", "ANALYZE", "Good: analyzing tables", Severity.INFO),
            (r"DESCRIBE\s+", "DESCRIBE", "Good: describing tables", Severity.INFO),
            (r"SHOW\s+", "SHOW", "Good: showing info", Severity.INFO),
            (r"USE\s+\w+", "USE database", "Good: selecting database", Severity.INFO),
            (r"SET\s+\w+", "SET variable", "Good: setting variable", Severity.INFO),
            (r"RESET\s+", "RESET", "Good: resetting", Severity.INFO),
            (r"PREPARE\s+", "PREPARE", "Good: preparing statement", Severity.INFO),
            (r"EXECUTE\s+", "EXECUTE", "Good: executing statement", Severity.INFO),
            (r"DEALLOCATE\s+", "DEALLOCATE", "Good: deallocating", Severity.INFO),
            (r"LOCK\s+TABLE", "LOCK TABLE", "Good: locking table", Severity.INFO),
            (r"UNLOCK\s+TABLE", "UNLOCK TABLE", "Good: unlocking table", Severity.INFO),
            (r"FLUSH\s+", "FLUSH", "Good: flushing", Severity.INFO),
            (r"PURGE\s+", "PURGE", "Good: purging", Severity.INFO),
            (r"OPTIMIZE\s+TABLE", "OPTIMIZE TABLE", "Good: optimizing", Severity.INFO),
            (r"REPAIR\s+TABLE", "REPAIR TABLE", "Good: repairing", Severity.INFO),
            (r"CHECK\s+TABLE", "CHECK TABLE", "Good: checking", Severity.INFO),
            (r"ANALYZE\s+TABLE", "ANALYZE TABLE", "Good: analyzing", Severity.INFO),
            (r"VACUUM\s+", "VACUUM", "Good: vacuuming", Severity.INFO),
            (r"REINDEX\s+", "REINDEX", "Good: reindexing", Severity.INFO),
            (r"CLONE\s+\w+", "CLONE", "Good: cloning", Severity.INFO),
            (r"IMPORT\s+", "IMPORT", "Good: importing", Severity.INFO),
            (r"EXPORT\s+", "EXPORT", "Good: exporting", Severity.INFO),
            # Connection management
            (r"connection.*pool|pool.*size|max.*connections|idle.*timeout|connection.*timeout", "Connection pooling", "Good: connection pooling", Severity.INFO),
            (r"reconnect|retry|failover|load.?balance|read.?replica|write.?primary", "Connection resilience", "Good: connection resilience", Severity.INFO),
            (r"sharding|partitioning|replication|backup|restore|point.?time.?recovery|wal|archive|log.?shipping", "Data management", "Good: data management", Severity.INFO),
            # Migration
            (r"migration|alembic|flyway|liquibase|django\.db\.migrations|prisma\.migrate|typeorm|knex|sequelize|drizzle|pgm", "Database migration", "Good: using migrations", Severity.INFO),
            # ORM
            (r"model\.save|model\.delete|model\.update|model\.create|model\.find|model\.filter|model\.query|model\.all|model\.get|model\.first|model\.count|model\.exists|model\.aggregate|model\.bulk_create|model\.bulk_update|model\.prefetch|model\.select_related|model\.annotate|model\.values|model\.values_list|model\.only|model\.defer|model\.select_for_update|model\.create_many|model\.update_many|model\.delete_many|model\.upsert|model\.bulk_upsert", "ORM operations", "Good: using ORM", Severity.INFO),
            # NoSQL
            (r"MongoDB|Cassandra|DynamoDB|CouchDB|Redis|Memcached|Elasticsearch|Neo4j|RethinkDB|ArangoDB|RavenDB|Firebase|Firestore|Supabase|PlanetScale|TiDB|CockroachDB|YugabyteDB|Vitess|ProxySQL|MaxScale|ClickHouse|Druid|InfluxDB|TimescaleDB|QuestDB|DuckDB", "NoSQL/NewSQL", "Good: using modern databases", Severity.INFO),
            # Caching
            (r"cache|redis|memcached|APC|OPcache|Varnish|Nginx|CDN|edge.*cache|browser.*cache|service.*worker|workbox|sw-precache", "Caching strategy", "Good: using caching", Severity.INFO),
            # Monitoring
            (r"monitor|metrics|prometheus|grafana|datadog|new.relic|app.dynamics|dynatrace|splunk|ELK|kibana|jaeger|zipkin|opentelemetry|openmetrics|statsd|graphite|collectd|telegraf|fluentd|fluentbit|logstash|filebeat|metricbeat|heartbeat|packetbeat|apm", "Monitoring/Observability", "Good: monitoring system", Severity.INFO),
        ]
        for line_num, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped.startswith('#') or stripped.startswith('--'):
                continue
            for pattern, message, severity in patterns:
                if re.search(pattern, line, re.IGNORECASE):
                    issues.append(self._create_issue(
                        file_path=file_path, line=line_num, message=message,
                        suggestion=message, severity=severity, code_snippet=stripped,
                    ))
        return issues
