"""
Comprehensive Java-specific rules.
"""

import re
from typing import Optional

from ..core.models import CodeIssue, Severity, IssueCategory
from ..core.rules import BaseRule


class JavaComprehensiveRules(BaseRule):
    """Java-specific comprehensive rules."""

    @property
    def name(self) -> str:
        return "java_comprehensive"

    @property
    def description(self) -> str:
        return "Java-specific comprehensive rules"

    @property
    def category(self) -> IssueCategory:
        return IssueCategory.BEST_PRACTICE

    @property
    def severity(self) -> Severity:
        return Severity.INFO

    def check(self, file_path: str, content: str) -> list[CodeIssue]:
        if not file_path.endswith('.java'):
            return []

        issues = []
        lines = content.splitlines()

        patterns = [
            # Java-specific patterns
            (r"(?:public|private|protected|static|final|abstract|synchronized|volatile|transient|native|strictfp|default)", "Java modifier", "Good: using modifiers", Severity.INFO),
            (r"(?:class|interface|enum|record|annotation|extends|implements|import|package)", "Java keyword", "Good: using Java keywords", Severity.INFO),
            (r"(?:if|else|for|while|do|switch|case|default|break|continue|return|throw|throws|try|catch|finally|assert)", "Java control flow", "Good: using control flow", Severity.INFO),
            (r"(?:new|instanceof|this|super|void|null|true|false)", "Java value", "Good: using Java values", Severity.INFO),
            (r"(?:int|long|short|byte|float|double|boolean|char|String|Integer|Long|Short|Byte|Float|Double|Boolean|Character|Object|Class|System|Math|String|StringBuilder|StringBuffer|Arrays|Collections|List|ArrayList|LinkedList|HashMap|TreeMap|LinkedHashMap|HashSet|TreeSet|LinkedHashSet|Queue|Deque|Stack|Vector|Hashtable|Properties|Date|Calendar|LocalDate|LocalTime|LocalDateTime|Instant|Duration|Period|ZonedDateTime|ZoneId|ZoneOffset|DateTimeFormatter|Optional|Stream|Collectors|CompletableFuture|ExecutorService|ThreadPoolExecutor|ScheduledExecutorService|CountDownLatch|CyclicBarrier|Semaphore|ReentrantLock|ReadWriteLock|StampedLock|Condition|AtomicInteger|AtomicLong|AtomicBoolean|AtomicReference|AtomicStampedReference|ConcurrentHashMap|ConcurrentLinkedQueue|ConcurrentLinkedDeque|CopyOnWriteArrayList|CopyOnWriteArraySet|BlockingQueue|ArrayBlockingQueue|LinkedBlockingQueue|PriorityBlockingQueue|SynchronousQueue|DelayQueue|LinkedTransferQueue)", "Java type", "Good: using Java types", Severity.INFO),
            (r"(?:System\.out\.println|System\.out\.print|System\.err\.println|System\.err\.print|System\.out\.printf|System\.out\.format|System\.in|System\.out|System\.err|System\.exit|System\.currentTimeMillis|System\.nanoTime|System\.arraycopy|System\.getenv|System\.getProperty|System\.setProperty|System\.clearProperty|System\.lineSeparator|System\.console|System\.inheritedChannel|System\.getSecurityManager|System\.setSecurityManager|System\.identityHashCode|System\.mapLibraryName|System\.load|System\.loadLibrary|System\.runFinalization|System\.gc|System\.runFinalizersOnExit|System\.halt|System\.getLogger)", "Java system", "Good: using System class", Severity.INFO),
            (r"(?:@Override|@Deprecated|@SuppressWarnings|@FunctionalInterface|@SafeVarargs|@Repeatable|@Retention|@Target|@Documented|@Inherited|@Native)", "Java annotation", "Good: using annotations", Severity.INFO),
            (r"(?:@Test|@Before|@After|@BeforeClass|@AfterClass|@BeforeMethod|@AfterMethod|@BeforeSuite|@AfterSuite|@BeforeTest|@AfterTest|@BeforeClass|@AfterClass|@DataProvider|@Factory|@Guice|@Listeners|@Test\(enabled|@Test\(timeOut|@Test\(dataProvider|@Test\(expectedExceptions)", "Java test annotation", "Good: using test annotations", Severity.INFO),
            (r"(?:@Autowired|@Qualifier|@Component|@Service|@Repository|@Controller|@RestController|@RequestMapping|@GetMapping|@PostMapping|@PutMapping|@DeleteMapping|@PatchMapping|@RequestBody|@ResponseBody|@PathVariable|@RequestParam|@RequestHeader|@CookieValue|@ModelAttribute|@SessionAttributes|@Valid|@Validated|@NotNull|@NotBlank|@NotEmpty|@Min|@Max|@Size|@Pattern|@Email|@Positive|@Negative|@PositiveOrZero|@NegativeOrZero|@Past|@PastOrPresent|@Future|@FutureOrPresent|@Digits|@DecimalMin|@DecimalMax)", "Java Spring annotation", "Good: using Spring annotations", Severity.INFO),
            (r"(?:@Entity|@Table|@Column|@Id|@GeneratedValue|@ManyToOne|@OneToMany|@ManyToMany|@OneToOne|@JoinColumn|@JoinTable|@MappedSuperclass|@Inheritance|@DiscriminatorColumn|@DiscriminatorValue|@Transient|@Lob|@Basic|@Enumerated|@Temporal|@Version|@NamedQuery|@NamedQueries|@NamedNativeQuery|@NamedNativeQueries)", "Java JPA annotation", "Good: using JPA annotations", Severity.INFO),
            (r"(?:@Inject|@Named|@Singleton|@RequestScoped|@SessionScoped|@ApplicationScoped|@Dependent|@Alternative|@Priority|@Vetoed|@Observes|@ObservesAsync|@Produces|@Disposes)", "Java CDI annotation", "Good: using CDI annotations", Severity.INFO),
            (r"(?:@XmlElement|@XmlAttribute|@XmlElementWrapper|@XmlRootElement|@XmlAccessorType|@XmlTransient|@XmlType|@XmlSchema)", "Java JAXB annotation", "Good: using JAXB annotations", Severity.INFO),
            (r"(?:@JsonInclude|@JsonProperty|@JsonIgnore|@JsonFormat|@JsonSerialize|@JsonDeserialize|@JsonCreator|@JsonValue|@JsonGetter|@JsonSetter|@JsonAnyGetter|@JsonAnySetter|@JsonAlias|@JsonTypeInfo|@JsonSubTypes|@JsonTypeName|@JsonClassDescription)", "Java Jackson annotation", "Good: using Jackson annotations", Severity.INFO),
            (r"(?:HashMap|TreeMap|LinkedHashMap|ConcurrentHashMap|Hashtable|Properties|EnumMap|WeakHashMap|IdentityHashMap|SortedMap|NavigableMap|NavigableSet|ConcurrentSkipListMap|ConcurrentSkipListSet|CopyOnWriteArrayList|CopyOnWriteArraySet|ArrayDeque|PriorityQueue|PriorityBlockingQueue|ArrayBlockingQueue|LinkedBlockingQueue|SynchronousQueue|DelayQueue|LinkedTransferQueue|ConcurrentLinkedQueue|ConcurrentLinkedDeque|ConcurrentHashMap\.KeySetView|ConcurrentHashMap\.KeySetView|ConcurrentHashMap\.ValuesView|ConcurrentHashMap\.EntrySetView)", "Java collection", "Good: using collections", Severity.INFO),
            (r"(?:ArrayList|LinkedList|Vector|Stack|CopyOnWriteArrayList|ArrayDeque|PriorityQueue|EnumSet|EnumMap|HashSet|TreeSet|LinkedHashSet|IdentityHashSet|ConcurrentSkipListSet|CopyOnWriteArraySet|JobControl|JobControl\.Status)", "Java List/Set", "Good: using List/Set", Severity.INFO),
            (r"(?:Stream\.of|Stream\.empty|Stream\.concat|Stream\.builder|Stream\.generate|Stream\.iterate|Stream\.range|Stream\.rangeClosed|Collectors\.toList|Collectors\.toSet|Collectors\.toMap|Collectors\.joining|Collectors\.summarizing|Collectors\.counting|Collectors\.groupingBy|Collectors\.partitioningBy|Collectors\.reducing|Collectors\.flatMapping|Collectors\.filtering|Collectors\.mapping|Collectors\.toUnmodifiableList|Collectors\.toUnmodifiableSet|Collectors\.toUnmodifiableMap)", "Java Stream", "Good: using Streams", Severity.INFO),
            (r"(?:CompletableFuture\.supplyAsync|CompletableFuture\.runAsync|CompletableFuture\.allOf|CompletableFuture\.anyOf|CompletableFuture\.completedFuture|CompletableFuture\.completedStage|CompletableFuture\.failedFuture|CompletableFuture\.failedStage|CompletableFuture\.completedFuture)", "Java CompletableFuture", "Good: using CompletableFutures", Severity.INFO),
            (r"(?:Thread\.currentThread|Thread\.sleep|Thread\.yield|Thread\.interrupted|Thread\.isInterrupted|Thread\.setName|Thread\.getName|Thread\.setPriority|Thread\.getPriority|Thread\.setDaemon|Thread\.isDaemon|Thread\.start|Thread\.join|Thread\.isAlive|Thread\.count|Thread\.getAllStackTraces|Thread\.getDefaultUncaughtExceptionHandler|Thread\.setDefaultUncaughtExceptionHandler|Thread\.onSpinWait)", "Java Thread", "Good: using Thread", Severity.INFO),
            (r"(?:synchronized\s*\(|synchronized\s+\w+|ReentrantLock|ReadWriteLock|StampedLock|Semaphore|CountDownLatch|CyclicBarrier|Phaser|Exchanger|LockSupport\.park|LockSupport\.unpark)", "Java concurrency", "Good: using concurrency", Severity.INFO),
            (r"(?:AtomicInteger|AtomicLong|AtomicBoolean|AtomicReference|AtomicStampedReference|AtomicMarkableReference|LongAdder|LongAccumulator|DoubleAdder|DoubleAccumulator|IntAdder|IntAccumulator)", "Java atomic", "Good: using atomic variables", Severity.INFO),
            (r"(?:ExecutorService|Executors\.newFixedThreadPool|Executors\.newCachedThreadPool|Executors\.newSingleThreadExecutor|Executors\.newScheduledThreadPool|Executors\.newSingleThreadScheduledExecutor|Executors\.newWorkStealingPool|ThreadPoolExecutor|ScheduledThreadPoolExecutor|ForkJoinPool|ScheduledExecutorService)", "Java executor", "Good: using executors", Severity.INFO),
            (r"(?:Instant|Duration|Period|LocalDate|LocalTime|LocalDateTime|ZonedDateTime|ZoneId|ZoneOffset|DateTimeFormatter|ChronoUnit|ChronoField|TemporalAdjuster|DateTimeParseException|Year|YearMonth|MonthDay|Month|DayOfWeek)", "Java time", "Good: using java.time", Severity.INFO),
            (r"(?:Pattern\.compile|Matcher\.matches|Matcher\.find|Matcher\.group|Matcher\.start|Matcher\.end|Matcher\.replaceAll|Matcher\.replaceFirst|Matcher\.reset|Matcher\.region|Matcher\.hasAnchoringBounds|Matcher\.useAnchoringBounds|Matcher\.hasTransparentBounds|Matcher\.useTransparentBounds|Matcher\.hitEnd|Matcher\.requireEnd|Matcher\.groupCount|Matcher\.group\(|Pattern\.matches|Pattern\.quote)", "Java regex", "Good: using regex", Severity.INFO),
            (r"(?:Files\.readString|Files\.writeString|Files\.lines|Files\.list|Files\.walk|Files\.find|Files\.copy|Files\.move|Files\.delete|Files\.createDirectory|Files\.createDirectories|Files\.exists|Files\.isRegularFile|Files\.isDirectory|Files\.size|Files\.getLastModifiedTime|Files\.setAttribute|Files\.getAttribute|Files\.readAttributes|Files\.newInputStream|Files\.newOutputStream|Files\.newBufferedReader|Files\.newBufferedWriter|Files\.newByteChannel|Files\.newDirectoryStream|Files\.probeContentType|Files\.getFileStore|Files\.isSameFile|Files\.isHidden|Files\.setPosixFilePermissions|Files\.getPosixFilePermissions|Files\.isSymbolicLink|Files\.readSymbolicLink|Files\.createSymbolicLink|Files\.createTempFile|Files\.createTempDirectory|Files\.readAllBytes|Files\.readAllLines|Files\.writeAllBytes|Files\.writeAllLines|Files\.newDirectoryStream|Files\.notExists|Files\.isReadable|Files\.isWritable|Files\.isExecutable|Files\.getOwner|Files\.setOwner|Files\.getFileAttributeView|Files\.readAttributes|Files\.setAttribute)", "Java NIO", "Good: using NIO", Severity.INFO),
            (r"(?:StringBuilder|StringBuffer|String\.format|String\.join|String\.valueOf|String\.copyValueOf|String\.intern|String\.isEmpty|String\.length|String\.charAt|String\.codePointAt|String\.codePointBefore|String\.codePointCount|String\.compareTo|String\.compareToIgnoreCase|String\.concat|String\.contains|String\.contentEquals|String\.endsWith|String\.equals|String\.equalsIgnoreCase|String\.getBytes|String\.getChars|String\.hashCode|String\.indexOf|String\.lastIndexOf|String\.matches|String\.offsetByCodePoints|String\.regionMatches|String\.replace|String\.replaceAll|String\.replaceFirst|String\.split|String\.startsWith|String\.substring|String\.toCharArray|String\.toLowerCase|String\.toString|String\.toUpperCase|String\.trim|String\.strip|String\.stripLeading|String\.stripTrailing|String\.isBlank|String\.repeat|String\.lines|String\.chars|String\.codePoints)", "Java String", "Good: using String methods", Severity.INFO),
            (r"(?:Files\.readString|Files\.writeString|Files\.lines|Files\.list|Files\.walk|Files\.find|Files\.copy|Files\.move|Files\.delete|Files\.createDirectory|Files\.createDirectories|Files\.exists|Files\.isRegularFile|Files\.isDirectory|Files\.size|Files\.getLastModifiedTime|Files\.setAttribute|Files\.getAttribute|Files\.readAttributes|Files\.newInputStream|Files\.newOutputStream|Files\.newBufferedReader|Files\.newBufferedWriter|Files\.newByteChannel|Files\.newDirectoryStream|Files\.probeContentType|Files\.getFileStore|Files\.isSameFile|Files\.isHidden|Files\.setPosixFilePermissions|Files\.getPosixFilePermissions|Files\.isSymbolicLink|Files\.readSymbolicLink|Files\.createSymbolicLink|Files\.createTempFile|Files\.createTempDirectory|Files\.readAllBytes|Files\.readAllLines|Files\.writeAllBytes|Files\.writeAllLines|Files\.newDirectoryStream|Files\.notExists|Files\.isReadable|Files\.isWritable|Files\.isExecutable|Files\.getOwner|Files\.setOwner|Files\.getFileAttributeView|Files\.readAttributes|Files\.setAttribute)", "Java NIO Files", "Good: using NIO Files", Severity.INFO),
            (r"(?:Optional\.of|Optional\.ofNullable|Optional\.empty|Optional\.get|Optional\.isPresent|Optional\.orElse|Optional\.orElseGet|Optional\.orElseThrow|Optional\.ifPresent|Optional\.ifPresentOrElse|Optional\.stream|Optional\.filter|Optional\.map|Optional\.flatMap|Optional\.or|Optional\.equals|Optional\.hashCode|Optional\.toString)", "Java Optional", "Good: using Optional", Severity.INFO),
            (r"(?:Objects\.requireNonNull|Objects\.checkIndex|Objects\.checkFromToIndex|Objects\.checkFromIndexSize|Objects\.isNull|Objects\.nonNull|Objects\.equals|Objects\.deepEquals|Objects\.hash|Objects\.toString|Objects\.compare|Objects\.isNull|Objects\.requireNonNullElse|Objects\.requireNonNullElseGet)", "Java Objects", "Good: using Objects utility", Severity.INFO),
            (r"(?:Collections\.unmodifiableList|Collections\.unmodifiableSet|Collections\.unmodifiableMap|Collections\.synchronizedList|Collections\.synchronizedSet|Collections\.synchronizedMap|Collections\.singletonList|Collections\.singleton|Collections\.singletonMap|Collections\.emptyList|Collections\.emptySet|Collections\.emptyMap|Collections\.nCopies|Collections\.enumeration|Collections\.list|Collections\.frequency|Collections\.reverse|Collections\.shuffle|Collections\.sort|Collections\.swap|Collections\.fill|Collections\.copy|Collections\.disjoint|Collections\.addAll|Collections\.rotate|Collections\.replaceAll|Collections\.indexOfSubList|Collections\.lastIndexOfSubList|Collections\.max|Collections\.min|Collections\.checkedList|Collections\.checkedSet|Collections\.checkedMap|Collections\.checkedCollection|Collections\.checkedQueue|Collections\.checkedNavigableSet|Collections\.checkedNavigableMap|Collections\.checkedSortedSet|Collections\.checkedSortedMap)", "Java Collections", "Good: using Collections utility", Severity.INFO),
            (r"(?:Arrays\.sort|Arrays\.binarySearch|Arrays\.copyOf|Arrays\.copyOfRange|Arrays\.fill|Arrays\.setAll|Arrays\.parallelPrefix|Arrays\.parallelSetAll|Arrays\.parallelSort|Arrays\.mismatch|Arrays\.equals|Arrays\.deepEquals|Arrays\.hashCode|Arrays\.deepHashCode|Arrays\.toString|Arrays\.deepToString|Arrays\.asList|Arrays\.stream|Arrays\.spliterator|Arrays\.compare|Arrays\.compareUnsigned|Arrays\.mismatch|Arrays\.sort|Arrays\.parallelSort|Arrays\.setAll|Arrays\.parallelPrefix|Arrays\.parallelSetAll)", "Java Arrays", "Good: using Arrays utility", Severity.INFO),
            (r"(?:HashMap|TreeMap|LinkedHashMap|ConcurrentHashMap|Hashtable|Properties|EnumMap|WeakHashMap|IdentityHashMap|SortedMap|NavigableMap|NavigableSet|ConcurrentSkipListMap|ConcurrentSkipListSet|CopyOnWriteArrayList|CopyOnWriteArraySet|ArrayDeque|PriorityQueue|PriorityBlockingQueue|ArrayBlockingQueue|LinkedBlockingQueue|SynchronousQueue|DelayQueue|LinkedTransferQueue|ConcurrentLinkedQueue|ConcurrentLinkedDeque|ConcurrentHashMap\.KeySetView|ConcurrentHashMap\.KeySetView|ConcurrentHashMap\.ValuesView|ConcurrentHashMap\.EntrySetView)", "Java Map", "Good: using Map", Severity.INFO),
            (r"(?:ArrayList|LinkedList|Vector|Stack|CopyOnWriteArrayList|ArrayDeque|PriorityQueue|EnumSet|EnumMap|HashSet|TreeSet|LinkedHashSet|IdentityHashSet|ConcurrentSkipListSet|CopyOnWriteArraySet|JobControl|JobControl\.Status)", "Java List/Set", "Good: using List/Set", Severity.INFO),
            (r"(?:CompletableFuture|CompletionStage|CompletionException|CompletionException|CompletionException)", "Java Future", "Good: using Futures", Severity.INFO),
            (r"(?:Thread|Runnable|Callable|Future|ExecutorService|ScheduledExecutorService|ForkJoinPool|CountDownLatch|CyclicBarrier|Semaphore|Phaser|Exchanger|LockSupport|ThreadLocal|InheritableThreadLocal|ThreadFactory|ThreadGroup|Thread\.UncaughtExceptionHandler)", "Java Concurrency", "Good: using concurrency", Severity.INFO),
            (r"(?:Path|Paths|File|FileReader|FileWriter|BufferedReader|BufferedWriter|FileReader|FileWriter|InputStream|OutputStream|FileInputStream|FileOutputStream|BufferedInputStream|BufferedOutputStream|DataInputStream|DataOutputStream|PrintStream|PrintWriter|ObjectInputStream|ObjectOutputStream|RandomAccessFile|FileChannel|MappedByteBuffer|FileLock)", "Java IO", "Good: using IO", Severity.INFO),
            (r"(?:Socket|ServerSocket|DatagramSocket|MulticastSocket|InetAddress|InetSocketAddress|URL|URLConnection|HttpURLConnection|HttpClient|HttpRequest|HttpResponse|WebSocket|URI|URLEncoder|URLDecoder)", "Java Networking", "Good: using networking", Severity.INFO),
            (r"(?:JDBC|Connection|DriverManager|Statement|PreparedStatement|ResultSet|ResultSetMetaData|DatabaseMetaData|BatchUpdateException|DataTruncation|SQLWarning|SQLException|SQLTransientException|SQLNonTransientException|SQLRecoverableException|SQLSyntaxErrorException|SQLIntegrityConstraintViolationException|SQLDataException|SQLTransactionRollbackException|SQLTimeoutException|SQLFeatureNotSupportedException|SQLClientInfoException|SQLInvalidAuthorizationSpecException|SQLNonTransientConnectionException|SQLTransientConnectionException|SQLRecoverableException|SQLNestedException)", "Java JDBC", "Good: using JDBC", Severity.INFO),
            (r"(?:JNDI|InitialContext|Context|NamingEnumeration|NameClassPair|Ref|Reference|Referenceable|ReferralException|AuthenticationException|CannotProceedException|CommunicationException|ConfigurationLimitException|InvalidNameException|LimitExceededException|LinkException|MalformedLinkException|NameAlreadyBoundException|NameNotFoundException|NamingException|NoInitialContextException|NotEmptyException|NoSuchAlgorithmException|OperationNotSupportedException|PartialResultException|ReferralException|ServiceUnavailableException|SizeLimitExceededException|TimeLimitExceededException|TooManyParametersException|UnsupportedOperationException)", "Java JNDI", "Good: using JNDI", Severity.INFO),
            (r"(?:JUnit|TestNG|Mockito|PowerMock|Easymock|JMock|Hamcrest|AssertJ|Truth|FEST|Awaitility|Spring Test|WireMock|REST Assured|Selenium|Appium|Cucumber|JBehave|SpecFlow|Serenity|Allure|ExtentReports)", "Java testing", "Good: using testing frameworks", Severity.INFO),
            (r"(?:Maven|Gradle|Ant|SBT|Ivy|Pip|Conda|npm|Yarn|Pnpm|Bun|NuGet|Paket|Cargo|Go|Mod|Composer|Gem|Bundler|Pub|Mix|Hex|CocoaPods|Carthage|SPM|Homebrew|APT|Yum|DNF|Pacman|Chocolatey|Winget|Scoop)", "Java build tool", "Good: using build tools", Severity.INFO),
            (r"(?:Spring|Spring Boot|Spring MVC|Spring Data|Spring Security|Spring Cloud|Spring Batch|Spring Integration|Spring WebFlux|Spring Reactive|Spring Web|Spring REST|Spring Boot|Spring Cloud|Spring Cloud Config|Spring Cloud Gateway|Spring Cloud Netflix|Spring Cloud Consul|Spring Cloud Zookeeper|Spring Cloud Kubernetes|Spring Cloud Vault|Spring Cloud Stream|Spring Cloud Function|Spring Cloud Contract|Spring Cloud OpenFeign|Spring Cloud LoadBalancer|Spring Cloud Circuit Breaker|Spring Cloud Sleuth|Spring Cloud Zipkin|Spring Cloud Micrometer|Spring Cloud Task|Spring Cloud Data Flow|Spring Cloud Commons|Spring Cloud Starter|Spring Cloud Bus|Spring Cloud Config|Spring Cloud Gateway|Spring Cloud Netflix|Spring Cloud Consul|Spring Cloud Zookeeper|Spring Cloud Kubernetes|Spring Cloud Vault|Spring Cloud Stream|Spring Cloud Function|Spring Cloud Contract|Spring Cloud OpenFeign|Spring Cloud LoadBalancer|Spring Cloud Circuit Breaker|Spring Cloud Sleuth|Spring Cloud Zipkin|Spring Cloud Micrometer|Spring Cloud Task|Spring Cloud Data Flow|Spring Cloud Commons|Spring Cloud Starter)", "Java Spring", "Good: using Spring", Severity.INFO),
            (r"(?:Hibernate|JPA|JDO|EclipseLink|OpenJPA|DataNucleus|ObjectDB|Speedy|MyBatis|iBATIS|SQL2O|JDBI|JOOQ|Spring Data JPA|Spring Data MongoDB|Spring Data Redis|Spring Data Elasticsearch|Spring Data Cassandra|Spring Data Couchbase|Spring Data Neo4j|Spring Data KeyValue|Spring Data REST|Spring Data JDBC|Spring Data R2DBC)", "Java ORM", "Good: using ORM", Severity.INFO),
            (r"(?:Jackson|Gson|JAXB|XStream|Fastjson|Jsoniter|Kotlin Serialization|Avro|Protocol Buffers|MessagePack|CBOR|BSON|YAML|XML|CSV|Properties|TOML|INI|JSON5|JSONL|NDJSON|JSONL)", "Java serialization", "Good: using serialization", Severity.INFO),
            (r"(?:Log4j|Logback|SLF4J|JUL|JCL|Log4j2|Log4j3|Tiny Logging|Flogger|JUL|Logback|SLF4J|JUL|JCL|Log4j2|Log4j3|Tiny Logging|Flogger)", "Java logging", "Good: using logging", Severity.INFO),
            (r"(?:JUnit|TestNG|Mockito|PowerMock|Easymock|JMock|Hamcrest|AssertJ|Truth|FEST|Awaitility|Spring Test|WireMock|REST Assured|Selenium|Appium|Cucumber|JBehave|SpecFlow|Serenity|Allure|ExtentReports)", "Java testing", "Good: using testing", Severity.INFO),
        ]

        for line_num, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped.startswith('//') or stripped.startswith('/*'):
                continue

            for pattern, message, suggestion, severity in patterns:
                if re.search(pattern, line, re.IGNORECASE):
                    issues.append(self._create_issue(
                        file_path=file_path,
                        line=line_num,
                        message=message,
                        suggestion=suggestion,
                        severity=severity,
                        code_snippet=stripped,
                    ))

        return issues
