"""Python patterns from official documentation (builtins, typing, stdlib)."""
import re
from ..core.models import CodeIssue, Severity, IssueCategory
from ..core.rules import BaseRule


class PythonDocumentationPatterns(BaseRule):
    @property
    def name(self) -> str:
        return "python_documentation"
    @property
    def description(self) -> str:
        return "Python patterns from official documentation"
    @property
    def category(self) -> IssueCategory:
        return IssueCategory.BEST_PRACTICE
    @property
    def severity(self) -> Severity:
        return Severity.INFO

    def check(self, file_path: str, content: str) -> list[CodeIssue]:
        issues = []
        lines = content.splitlines()
        patterns = [
            (r"\bArithmeticError\s*\(", "Built-in ArithmeticError", "Good: built-in function", Severity.INFO),
            (r"\bAssertionError\s*\(", "Built-in AssertionError", "Good: built-in function", Severity.INFO),
            (r"\bAttributeError\s*\(", "Built-in AttributeError", "Good: built-in function", Severity.INFO),
            (r"\bBaseException\s*\(", "Built-in BaseException", "Good: built-in function", Severity.INFO),
            (r"\bBaseExceptionGroup\s*\(", "Built-in BaseExceptionGroup", "Good: built-in function", Severity.INFO),
            (r"\bBlockingIOError\s*\(", "Built-in BlockingIOError", "Good: built-in function", Severity.INFO),
            (r"\bBrokenPipeError\s*\(", "Built-in BrokenPipeError", "Good: built-in function", Severity.INFO),
            (r"\bBufferError\s*\(", "Built-in BufferError", "Good: built-in function", Severity.INFO),
            (r"\bBytesWarning\s*\(", "Built-in BytesWarning", "Good: built-in function", Severity.INFO),
            (r"\bChildProcessError\s*\(", "Built-in ChildProcessError", "Good: built-in function", Severity.INFO),
            (r"\bConnectionAbortedError\s*\(", "Built-in ConnectionAbortedError", "Good: built-in function", Severity.INFO),
            (r"\bConnectionError\s*\(", "Built-in ConnectionError", "Good: built-in function", Severity.INFO),
            (r"\bConnectionRefusedError\s*\(", "Built-in ConnectionRefusedError", "Good: built-in function", Severity.INFO),
            (r"\bConnectionResetError\s*\(", "Built-in ConnectionResetError", "Good: built-in function", Severity.INFO),
            (r"\bDeprecationWarning\s*\(", "Built-in DeprecationWarning", "Good: built-in function", Severity.INFO),
            (r"\bEOFError\s*\(", "Built-in EOFError", "Good: built-in function", Severity.INFO),
            (r"\bEncodingWarning\s*\(", "Built-in EncodingWarning", "Good: built-in function", Severity.INFO),
            (r"\bEnvironmentError\s*\(", "Built-in EnvironmentError", "Good: built-in function", Severity.INFO),
            (r"\bException\s*\(", "Built-in Exception", "Good: built-in function", Severity.INFO),
            (r"\bExceptionGroup\s*\(", "Built-in ExceptionGroup", "Good: built-in function", Severity.INFO),
            (r"\bFileExistsError\s*\(", "Built-in FileExistsError", "Good: built-in function", Severity.INFO),
            (r"\bFileNotFoundError\s*\(", "Built-in FileNotFoundError", "Good: built-in function", Severity.INFO),
            (r"\bFloatingPointError\s*\(", "Built-in FloatingPointError", "Good: built-in function", Severity.INFO),
            (r"\bFutureWarning\s*\(", "Built-in FutureWarning", "Good: built-in function", Severity.INFO),
            (r"\bGeneratorExit\s*\(", "Built-in GeneratorExit", "Good: built-in function", Severity.INFO),
            (r"\bIOError\s*\(", "Built-in IOError", "Good: built-in function", Severity.INFO),
            (r"\bImportError\s*\(", "Built-in ImportError", "Good: built-in function", Severity.INFO),
            (r"\bImportWarning\s*\(", "Built-in ImportWarning", "Good: built-in function", Severity.INFO),
            (r"\bIndentationError\s*\(", "Built-in IndentationError", "Good: built-in function", Severity.INFO),
            (r"\bIndexError\s*\(", "Built-in IndexError", "Good: built-in function", Severity.INFO),
            (r"\bInterruptedError\s*\(", "Built-in InterruptedError", "Good: built-in function", Severity.INFO),
            (r"\bIsADirectoryError\s*\(", "Built-in IsADirectoryError", "Good: built-in function", Severity.INFO),
            (r"\bKeyError\s*\(", "Built-in KeyError", "Good: built-in function", Severity.INFO),
            (r"\bKeyboardInterrupt\s*\(", "Built-in KeyboardInterrupt", "Good: built-in function", Severity.INFO),
            (r"\bLookupError\s*\(", "Built-in LookupError", "Good: built-in function", Severity.INFO),
            (r"\bMemoryError\s*\(", "Built-in MemoryError", "Good: built-in function", Severity.INFO),
            (r"\bModuleNotFoundError\s*\(", "Built-in ModuleNotFoundError", "Good: built-in function", Severity.INFO),
            (r"\bNameError\s*\(", "Built-in NameError", "Good: built-in function", Severity.INFO),
            (r"\bNotADirectoryError\s*\(", "Built-in NotADirectoryError", "Good: built-in function", Severity.INFO),
            (r"\bNotImplementedError\s*\(", "Built-in NotImplementedError", "Good: built-in function", Severity.INFO),
            (r"\bOSError\s*\(", "Built-in OSError", "Good: built-in function", Severity.INFO),
            (r"\bOverflowError\s*\(", "Built-in OverflowError", "Good: built-in function", Severity.INFO),
            (r"\bPendingDeprecationWarning\s*\(", "Built-in PendingDeprecationWarning", "Good: built-in function", Severity.INFO),
            (r"\bPermissionError\s*\(", "Built-in PermissionError", "Good: built-in function", Severity.INFO),
            (r"\bProcessLookupError\s*\(", "Built-in ProcessLookupError", "Good: built-in function", Severity.INFO),
            (r"\bRecursionError\s*\(", "Built-in RecursionError", "Good: built-in function", Severity.INFO),
            (r"\bReferenceError\s*\(", "Built-in ReferenceError", "Good: built-in function", Severity.INFO),
            (r"\bResourceWarning\s*\(", "Built-in ResourceWarning", "Good: built-in function", Severity.INFO),
            (r"\bRuntimeError\s*\(", "Built-in RuntimeError", "Good: built-in function", Severity.INFO),
            (r"\bRuntimeWarning\s*\(", "Built-in RuntimeWarning", "Good: built-in function", Severity.INFO),
            (r"\bStopAsyncIteration\s*\(", "Built-in StopAsyncIteration", "Good: built-in function", Severity.INFO),
            (r"\bStopIteration\s*\(", "Built-in StopIteration", "Good: built-in function", Severity.INFO),
            (r"\bSyntaxError\s*\(", "Built-in SyntaxError", "Good: built-in function", Severity.INFO),
            (r"\bSyntaxWarning\s*\(", "Built-in SyntaxWarning", "Good: built-in function", Severity.INFO),
            (r"\bSystemError\s*\(", "Built-in SystemError", "Good: built-in function", Severity.INFO),
            (r"\bSystemExit\s*\(", "Built-in SystemExit", "Good: built-in function", Severity.INFO),
            (r"\bTabError\s*\(", "Built-in TabError", "Good: built-in function", Severity.INFO),
            (r"\bTimeoutError\s*\(", "Built-in TimeoutError", "Good: built-in function", Severity.INFO),
            (r"\bTypeError\s*\(", "Built-in TypeError", "Good: built-in function", Severity.INFO),
            (r"\bUnboundLocalError\s*\(", "Built-in UnboundLocalError", "Good: built-in function", Severity.INFO),
            (r"\bUnicodeDecodeError\s*\(", "Built-in UnicodeDecodeError", "Good: built-in function", Severity.INFO),
            (r"\bUnicodeEncodeError\s*\(", "Built-in UnicodeEncodeError", "Good: built-in function", Severity.INFO),
            (r"\bUnicodeError\s*\(", "Built-in UnicodeError", "Good: built-in function", Severity.INFO),
            (r"\bUnicodeTranslateError\s*\(", "Built-in UnicodeTranslateError", "Good: built-in function", Severity.INFO),
            (r"\bUnicodeWarning\s*\(", "Built-in UnicodeWarning", "Good: built-in function", Severity.INFO),
            (r"\bUserWarning\s*\(", "Built-in UserWarning", "Good: built-in function", Severity.INFO),
            (r"\bValueError\s*\(", "Built-in ValueError", "Good: built-in function", Severity.INFO),
            (r"\bWarning\s*\(", "Built-in Warning", "Good: built-in function", Severity.INFO),
            (r"\bZeroDivisionError\s*\(", "Built-in ZeroDivisionError", "Good: built-in function", Severity.INFO),
            (r"\babs\s*\(", "Built-in abs", "Good: built-in function", Severity.INFO),
            (r"\baiter\s*\(", "Built-in aiter", "Good: built-in function", Severity.INFO),
            (r"\ball\s*\(", "Built-in all", "Good: built-in function", Severity.INFO),
            (r"\banext\s*\(", "Built-in anext", "Good: built-in function", Severity.INFO),
            (r"\bany\s*\(", "Built-in any", "Good: built-in function", Severity.INFO),
            (r"\bascii\s*\(", "Built-in ascii", "Good: built-in function", Severity.INFO),
            (r"\bbin\s*\(", "Built-in bin", "Good: built-in function", Severity.INFO),
            (r"\bbool\s*\(", "Built-in bool", "Good: built-in function", Severity.INFO),
            (r"\bbreakpoint\s*\(", "Built-in breakpoint", "Good: built-in function", Severity.INFO),
            (r"\bbytearray\s*\(", "Built-in bytearray", "Good: built-in function", Severity.INFO),
            (r"\bbytes\s*\(", "Built-in bytes", "Good: built-in function", Severity.INFO),
            (r"\bcallable\s*\(", "Built-in callable", "Good: built-in function", Severity.INFO),
            (r"\bchr\s*\(", "Built-in chr", "Good: built-in function", Severity.INFO),
            (r"\bclassmethod\s*\(", "Built-in classmethod", "Good: built-in function", Severity.INFO),
            (r"\bcompile\s*\(", "Built-in compile", "Good: built-in function", Severity.INFO),
            (r"\bcomplex\s*\(", "Built-in complex", "Good: built-in function", Severity.INFO),
            (r"\bcopyright\s*\(", "Built-in copyright", "Good: built-in function", Severity.INFO),
            (r"\bcredits\s*\(", "Built-in credits", "Good: built-in function", Severity.INFO),
            (r"\bdelattr\s*\(", "Built-in delattr", "Good: built-in function", Severity.INFO),
            (r"\bdict\s*\(", "Built-in dict", "Good: built-in function", Severity.INFO),
            (r"\bdir\s*\(", "Built-in dir", "Good: built-in function", Severity.INFO),
            (r"\bdivmod\s*\(", "Built-in divmod", "Good: built-in function", Severity.INFO),
            (r"\benumerate\s*\(", "Built-in enumerate", "Good: built-in function", Severity.INFO),
            (r"\beval\s*\(", "Built-in eval", "Good: built-in function", Severity.INFO),
            (r"\bexec\s*\(", "Built-in exec", "Good: built-in function", Severity.INFO),
            (r"\bexit\s*\(", "Built-in exit", "Good: built-in function", Severity.INFO),
            (r"\bfilter\s*\(", "Built-in filter", "Good: built-in function", Severity.INFO),
            (r"\bfloat\s*\(", "Built-in float", "Good: built-in function", Severity.INFO),
            (r"\bformat\s*\(", "Built-in format", "Good: built-in function", Severity.INFO),
            (r"\bfrozenset\s*\(", "Built-in frozenset", "Good: built-in function", Severity.INFO),
            (r"\bgetattr\s*\(", "Built-in getattr", "Good: built-in function", Severity.INFO),
            (r"\bglobals\s*\(", "Built-in globals", "Good: built-in function", Severity.INFO),
            (r"\bhasattr\s*\(", "Built-in hasattr", "Good: built-in function", Severity.INFO),
            (r"\bhash\s*\(", "Built-in hash", "Good: built-in function", Severity.INFO),
            (r"\bhelp\s*\(", "Built-in help", "Good: built-in function", Severity.INFO),
            (r"\bhex\s*\(", "Built-in hex", "Good: built-in function", Severity.INFO),
            (r"\bid\s*\(", "Built-in id", "Good: built-in function", Severity.INFO),
            (r"\binput\s*\(", "Built-in input", "Good: built-in function", Severity.INFO),
            (r"\bint\s*\(", "Built-in int", "Good: built-in function", Severity.INFO),
            (r"\bisinstance\s*\(", "Built-in isinstance", "Good: built-in function", Severity.INFO),
            (r"\bissubclass\s*\(", "Built-in issubclass", "Good: built-in function", Severity.INFO),
            (r"\biter\s*\(", "Built-in iter", "Good: built-in function", Severity.INFO),
            (r"\blen\s*\(", "Built-in len", "Good: built-in function", Severity.INFO),
            (r"\blicense\s*\(", "Built-in license", "Good: built-in function", Severity.INFO),
            (r"\blist\s*\(", "Built-in list", "Good: built-in function", Severity.INFO),
            (r"\blocals\s*\(", "Built-in locals", "Good: built-in function", Severity.INFO),
            (r"\bmap\s*\(", "Built-in map", "Good: built-in function", Severity.INFO),
            (r"\bmax\s*\(", "Built-in max", "Good: built-in function", Severity.INFO),
            (r"\bmemoryview\s*\(", "Built-in memoryview", "Good: built-in function", Severity.INFO),
            (r"\bmin\s*\(", "Built-in min", "Good: built-in function", Severity.INFO),
            (r"\bnext\s*\(", "Built-in next", "Good: built-in function", Severity.INFO),
            (r"\bobject\s*\(", "Built-in object", "Good: built-in function", Severity.INFO),
            (r"\boct\s*\(", "Built-in oct", "Good: built-in function", Severity.INFO),
            (r"\bopen\s*\(", "Built-in open", "Good: built-in function", Severity.INFO),
            (r"\bord\s*\(", "Built-in ord", "Good: built-in function", Severity.INFO),
            (r"\bpow\s*\(", "Built-in pow", "Good: built-in function", Severity.INFO),
            (r"\bprint\s*\(", "Built-in print", "Good: built-in function", Severity.INFO),
            (r"\bproperty\s*\(", "Built-in property", "Good: built-in function", Severity.INFO),
            (r"\bquit\s*\(", "Built-in quit", "Good: built-in function", Severity.INFO),
            (r"\brange\s*\(", "Built-in range", "Good: built-in function", Severity.INFO),
            (r"\brepr\s*\(", "Built-in repr", "Good: built-in function", Severity.INFO),
            (r"\breversed\s*\(", "Built-in reversed", "Good: built-in function", Severity.INFO),
            (r"\bround\s*\(", "Built-in round", "Good: built-in function", Severity.INFO),
            (r"\bset\s*\(", "Built-in set", "Good: built-in function", Severity.INFO),
            (r"\bsetattr\s*\(", "Built-in setattr", "Good: built-in function", Severity.INFO),
            (r"\bslice\s*\(", "Built-in slice", "Good: built-in function", Severity.INFO),
            (r"\bsorted\s*\(", "Built-in sorted", "Good: built-in function", Severity.INFO),
            (r"\bstaticmethod\s*\(", "Built-in staticmethod", "Good: built-in function", Severity.INFO),
            (r"\bstr\s*\(", "Built-in str", "Good: built-in function", Severity.INFO),
            (r"\bsum\s*\(", "Built-in sum", "Good: built-in function", Severity.INFO),
            (r"\bsuper\s*\(", "Built-in super", "Good: built-in function", Severity.INFO),
            (r"\btuple\s*\(", "Built-in tuple", "Good: built-in function", Severity.INFO),
            (r"\btype\s*\(", "Built-in type", "Good: built-in function", Severity.INFO),
            (r"\bvars\s*\(", "Built-in vars", "Good: built-in function", Severity.INFO),
            (r"\bzip\s*\(", "Built-in zip", "Good: built-in function", Severity.INFO),
            (r"\bArithmeticError\b", "Exception ArithmeticError", "Good: exception handling", Severity.INFO),
            (r"\bAssertionError\b", "Exception AssertionError", "Good: exception handling", Severity.INFO),
            (r"\bAttributeError\b", "Exception AttributeError", "Good: exception handling", Severity.INFO),
            (r"\bBaseException\b", "Exception BaseException", "Good: exception handling", Severity.INFO),
            (r"\bBaseExceptionGroup\b", "Exception BaseExceptionGroup", "Good: exception handling", Severity.INFO),
            (r"\bBlockingIOError\b", "Exception BlockingIOError", "Good: exception handling", Severity.INFO),
            (r"\bBrokenPipeError\b", "Exception BrokenPipeError", "Good: exception handling", Severity.INFO),
            (r"\bBufferError\b", "Exception BufferError", "Good: exception handling", Severity.INFO),
            (r"\bBytesWarning\b", "Exception BytesWarning", "Good: exception handling", Severity.INFO),
            (r"\bChildProcessError\b", "Exception ChildProcessError", "Good: exception handling", Severity.INFO),
            (r"\bConnectionAbortedError\b", "Exception ConnectionAbortedError", "Good: exception handling", Severity.INFO),
            (r"\bConnectionError\b", "Exception ConnectionError", "Good: exception handling", Severity.INFO),
            (r"\bConnectionRefusedError\b", "Exception ConnectionRefusedError", "Good: exception handling", Severity.INFO),
            (r"\bConnectionResetError\b", "Exception ConnectionResetError", "Good: exception handling", Severity.INFO),
            (r"\bDeprecationWarning\b", "Exception DeprecationWarning", "Good: exception handling", Severity.INFO),
            (r"\bEOFError\b", "Exception EOFError", "Good: exception handling", Severity.INFO),
            (r"\bEncodingWarning\b", "Exception EncodingWarning", "Good: exception handling", Severity.INFO),
            (r"\bEnvironmentError\b", "Exception EnvironmentError", "Good: exception handling", Severity.INFO),
            (r"\bException\b", "Exception Exception", "Good: exception handling", Severity.INFO),
            (r"\bExceptionGroup\b", "Exception ExceptionGroup", "Good: exception handling", Severity.INFO),
            (r"\bFileExistsError\b", "Exception FileExistsError", "Good: exception handling", Severity.INFO),
            (r"\bFileNotFoundError\b", "Exception FileNotFoundError", "Good: exception handling", Severity.INFO),
            (r"\bFloatingPointError\b", "Exception FloatingPointError", "Good: exception handling", Severity.INFO),
            (r"\bFutureWarning\b", "Exception FutureWarning", "Good: exception handling", Severity.INFO),
            (r"\bGeneratorExit\b", "Exception GeneratorExit", "Good: exception handling", Severity.INFO),
            (r"\bIOError\b", "Exception IOError", "Good: exception handling", Severity.INFO),
            (r"\bImportError\b", "Exception ImportError", "Good: exception handling", Severity.INFO),
            (r"\bImportWarning\b", "Exception ImportWarning", "Good: exception handling", Severity.INFO),
            (r"\bIndentationError\b", "Exception IndentationError", "Good: exception handling", Severity.INFO),
            (r"\bIndexError\b", "Exception IndexError", "Good: exception handling", Severity.INFO),
            (r"\bInterruptedError\b", "Exception InterruptedError", "Good: exception handling", Severity.INFO),
            (r"\bIsADirectoryError\b", "Exception IsADirectoryError", "Good: exception handling", Severity.INFO),
            (r"\bKeyError\b", "Exception KeyError", "Good: exception handling", Severity.INFO),
            (r"\bKeyboardInterrupt\b", "Exception KeyboardInterrupt", "Good: exception handling", Severity.INFO),
            (r"\bLookupError\b", "Exception LookupError", "Good: exception handling", Severity.INFO),
            (r"\bMemoryError\b", "Exception MemoryError", "Good: exception handling", Severity.INFO),
            (r"\bModuleNotFoundError\b", "Exception ModuleNotFoundError", "Good: exception handling", Severity.INFO),
            (r"\bNameError\b", "Exception NameError", "Good: exception handling", Severity.INFO),
            (r"\bNotADirectoryError\b", "Exception NotADirectoryError", "Good: exception handling", Severity.INFO),
            (r"\bNotImplementedError\b", "Exception NotImplementedError", "Good: exception handling", Severity.INFO),
            (r"\bOSError\b", "Exception OSError", "Good: exception handling", Severity.INFO),
            (r"\bOverflowError\b", "Exception OverflowError", "Good: exception handling", Severity.INFO),
            (r"\bPendingDeprecationWarning\b", "Exception PendingDeprecationWarning", "Good: exception handling", Severity.INFO),
            (r"\bPermissionError\b", "Exception PermissionError", "Good: exception handling", Severity.INFO),
            (r"\bProcessLookupError\b", "Exception ProcessLookupError", "Good: exception handling", Severity.INFO),
            (r"\bRecursionError\b", "Exception RecursionError", "Good: exception handling", Severity.INFO),
            (r"\bReferenceError\b", "Exception ReferenceError", "Good: exception handling", Severity.INFO),
            (r"\bResourceWarning\b", "Exception ResourceWarning", "Good: exception handling", Severity.INFO),
            (r"\bRuntimeError\b", "Exception RuntimeError", "Good: exception handling", Severity.INFO),
            (r"\bRuntimeWarning\b", "Exception RuntimeWarning", "Good: exception handling", Severity.INFO),
            (r"\bStopAsyncIteration\b", "Exception StopAsyncIteration", "Good: exception handling", Severity.INFO),
            (r"\bStopIteration\b", "Exception StopIteration", "Good: exception handling", Severity.INFO),
            (r"\bSyntaxError\b", "Exception SyntaxError", "Good: exception handling", Severity.INFO),
            (r"\bSyntaxWarning\b", "Exception SyntaxWarning", "Good: exception handling", Severity.INFO),
            (r"\bSystemError\b", "Exception SystemError", "Good: exception handling", Severity.INFO),
            (r"\bSystemExit\b", "Exception SystemExit", "Good: exception handling", Severity.INFO),
            (r"\bTabError\b", "Exception TabError", "Good: exception handling", Severity.INFO),
            (r"\bTimeoutError\b", "Exception TimeoutError", "Good: exception handling", Severity.INFO),
            (r"\bTypeError\b", "Exception TypeError", "Good: exception handling", Severity.INFO),
            (r"\bUnboundLocalError\b", "Exception UnboundLocalError", "Good: exception handling", Severity.INFO),
            (r"\bUnicodeDecodeError\b", "Exception UnicodeDecodeError", "Good: exception handling", Severity.INFO),
            (r"\bUnicodeEncodeError\b", "Exception UnicodeEncodeError", "Good: exception handling", Severity.INFO),
            (r"\bUnicodeError\b", "Exception UnicodeError", "Good: exception handling", Severity.INFO),
            (r"\bUnicodeTranslateError\b", "Exception UnicodeTranslateError", "Good: exception handling", Severity.INFO),
            (r"\bUnicodeWarning\b", "Exception UnicodeWarning", "Good: exception handling", Severity.INFO),
            (r"\bUserWarning\b", "Exception UserWarning", "Good: exception handling", Severity.INFO),
            (r"\bValueError\b", "Exception ValueError", "Good: exception handling", Severity.INFO),
            (r"\bWarning\b", "Exception Warning", "Good: exception handling", Severity.INFO),
            (r"\bZeroDivisionError\b", "Exception ZeroDivisionError", "Good: exception handling", Severity.INFO),
            (r"\bAnnotated\b", "Typing Annotated", "Good: type annotation", Severity.INFO),
            (r"\bAny\b", "Typing Any", "Good: type annotation", Severity.INFO),
            (r"\bAsyncContextManager\b", "Typing AsyncContextManager", "Good: type annotation", Severity.INFO),
            (r"\bAsyncGenerator\b", "Typing AsyncGenerator", "Good: type annotation", Severity.INFO),
            (r"\bAsyncIterable\b", "Typing AsyncIterable", "Good: type annotation", Severity.INFO),
            (r"\bAsyncIterator\b", "Typing AsyncIterator", "Good: type annotation", Severity.INFO),
            (r"\bAwaitable\b", "Typing Awaitable", "Good: type annotation", Severity.INFO),
            (r"\bCallable\b", "Typing Callable", "Good: type annotation", Severity.INFO),
            (r"\bClassVar\b", "Typing ClassVar", "Good: type annotation", Severity.INFO),
            (r"\bContextManager\b", "Typing ContextManager", "Good: type annotation", Severity.INFO),
            (r"\bCoroutine\b", "Typing Coroutine", "Good: type annotation", Severity.INFO),
            (r"\bDict\b", "Typing Dict", "Good: type annotation", Severity.INFO),
            (r"\bFinal\b", "Typing Final", "Good: type annotation", Severity.INFO),
            (r"\bGenerator\b", "Typing Generator", "Good: type annotation", Severity.INFO),
            (r"\bIterable\b", "Typing Iterable", "Good: type annotation", Severity.INFO),
            (r"\bIterator\b", "Typing Iterator", "Good: type annotation", Severity.INFO),
            (r"\bList\b", "Typing List", "Good: type annotation", Severity.INFO),
            (r"\bLiteral\b", "Typing Literal", "Good: type annotation", Severity.INFO),
            (r"\bMapping\b", "Typing Mapping", "Good: type annotation", Severity.INFO),
            (r"\bMutableMapping\b", "Typing MutableMapping", "Good: type annotation", Severity.INFO),
            (r"\bMutableSequence\b", "Typing MutableSequence", "Good: type annotation", Severity.INFO),
            (r"\bNamedTuple\b", "Typing NamedTuple", "Good: type annotation", Severity.INFO),
            (r"\bNotRequired\b", "Typing NotRequired", "Good: type annotation", Severity.INFO),
            (r"\bOptional\b", "Typing Optional", "Good: type annotation", Severity.INFO),
            (r"\bParamSpec\b", "Typing ParamSpec", "Good: type annotation", Severity.INFO),
            (r"\bProtocol\b", "Typing Protocol", "Good: type annotation", Severity.INFO),
            (r"\bRequired\b", "Typing Required", "Good: type annotation", Severity.INFO),
            (r"\bSelf\b", "Typing Self", "Good: type annotation", Severity.INFO),
            (r"\bSequence\b", "Typing Sequence", "Good: type annotation", Severity.INFO),
            (r"\bSet\b", "Typing Set", "Good: type annotation", Severity.INFO),
            (r"\bTuple\b", "Typing Tuple", "Good: type annotation", Severity.INFO),
            (r"\bType\b", "Typing Type", "Good: type annotation", Severity.INFO),
            (r"\bTypeVar\b", "Typing TypeVar", "Good: type annotation", Severity.INFO),
            (r"\bTypedDict\b", "Typing TypedDict", "Good: type annotation", Severity.INFO),
            (r"\bUnion\b", "Typing Union", "Good: type annotation", Severity.INFO),
            (r"\bimport\s+os\b|\bfrom\s+os\s+import", "Import os", "Good: standard library", Severity.INFO),
            (r"\bimport\s+sys\b|\bfrom\s+sys\s+import", "Import sys", "Good: standard library", Severity.INFO),
            (r"\bimport\s+json\b|\bfrom\s+json\s+import", "Import json", "Good: standard library", Severity.INFO),
            (r"\bimport\s+re\b|\bfrom\s+re\s+import", "Import re", "Good: standard library", Severity.INFO),
            (r"\bimport\s+datetime\b|\bfrom\s+datetime\s+import", "Import datetime", "Good: standard library", Severity.INFO),
            (r"\bimport\s+time\b|\bfrom\s+time\s+import", "Import time", "Good: standard library", Severity.INFO),
            (r"\bimport\s+collections\b|\bfrom\s+collections\s+import", "Import collections", "Good: standard library", Severity.INFO),
            (r"\bimport\s+itertools\b|\bfrom\s+itertools\s+import", "Import itertools", "Good: standard library", Severity.INFO),
            (r"\bimport\s+functools\b|\bfrom\s+functools\s+import", "Import functools", "Good: standard library", Severity.INFO),
            (r"\bimport\s+pathlib\b|\bfrom\s+pathlib\s+import", "Import pathlib", "Good: standard library", Severity.INFO),
            (r"\bimport\s+io\b|\bfrom\s+io\s+import", "Import io", "Good: standard library", Severity.INFO),
            (r"\bimport\s+abc\b|\bfrom\s+abc\s+import", "Import abc", "Good: standard library", Severity.INFO),
            (r"\bimport\s+typing\b|\bfrom\s+typing\s+import", "Import typing", "Good: standard library", Severity.INFO),
            (r"\bimport\s+dataclasses\b|\bfrom\s+dataclasses\s+import", "Import dataclasses", "Good: standard library", Severity.INFO),
            (r"\bimport\s+enum\b|\bfrom\s+enum\s+import", "Import enum", "Good: standard library", Severity.INFO),
            (r"\bimport\s+math\b|\bfrom\s+math\s+import", "Import math", "Good: standard library", Severity.INFO),
            (r"\bimport\s+random\b|\bfrom\s+random\s+import", "Import random", "Good: standard library", Severity.INFO),
            (r"\bimport\s+string\b|\bfrom\s+string\s+import", "Import string", "Good: standard library", Severity.INFO),
            (r"\bimport\s+textwrap\b|\bfrom\s+textwrap\s+import", "Import textwrap", "Good: standard library", Severity.INFO),
            (r"\bimport\s+logging\b|\bfrom\s+logging\s+import", "Import logging", "Good: standard library", Severity.INFO),
            (r"\bimport\s+argparse\b|\bfrom\s+argparse\s+import", "Import argparse", "Good: standard library", Severity.INFO),
            (r"\bimport\s+subprocess\b|\bfrom\s+subprocess\s+import", "Import subprocess", "Good: standard library", Severity.INFO),
            (r"\bimport\s+threading\b|\bfrom\s+threading\s+import", "Import threading", "Good: standard library", Severity.INFO),
            (r"\bimport\s+multiprocessing\b|\bfrom\s+multiprocessing\s+import", "Import multiprocessing", "Good: standard library", Severity.INFO),
            (r"\bimport\s+unittest\b|\bfrom\s+unittest\s+import", "Import unittest", "Good: standard library", Severity.INFO),
            (r"\bimport\s+pytest\b|\bfrom\s+pytest\s+import", "Import pytest", "Good: standard library", Severity.INFO),
            (r"\bimport\s+asyncio\b|\bfrom\s+asyncio\s+import", "Import asyncio", "Good: standard library", Severity.INFO),
            (r"\bimport\s+socket\b|\bfrom\s+socket\s+import", "Import socket", "Good: standard library", Severity.INFO),
            (r"\bimport\s+http\b|\bfrom\s+http\s+import", "Import http", "Good: standard library", Severity.INFO),
            (r"\bimport\s+urllib\b|\bfrom\s+urllib\s+import", "Import urllib", "Good: standard library", Severity.INFO),
            (r"\bimport\s+email\b|\bfrom\s+email\s+import", "Import email", "Good: standard library", Severity.INFO),
            (r"\bimport\s+html\b|\bfrom\s+html\s+import", "Import html", "Good: standard library", Severity.INFO),
            (r"\bimport\s+xml\b|\bfrom\s+xml\s+import", "Import xml", "Good: standard library", Severity.INFO),
            (r"\bimport\s+csv\b|\bfrom\s+csv\s+import", "Import csv", "Good: standard library", Severity.INFO),
            (r"\bimport\s+configparser\b|\bfrom\s+configparser\s+import", "Import configparser", "Good: standard library", Severity.INFO),
            (r"\bimport\s+secrets\b|\bfrom\s+secrets\s+import", "Import secrets", "Good: standard library", Severity.INFO),
            (r"\bimport\s+hashlib\b|\bfrom\s+hashlib\s+import", "Import hashlib", "Good: standard library", Severity.INFO),
            (r"\bimport\s+hmac\b|\bfrom\s+hmac\s+import", "Import hmac", "Good: standard library", Severity.INFO),
            (r"\bimport\s+base64\b|\bfrom\s+base64\s+import", "Import base64", "Good: standard library", Severity.INFO),
            (r"\bimport\s+struct\b|\bfrom\s+struct\s+import", "Import struct", "Good: standard library", Severity.INFO),
            (r"\bimport\s+pickle\b|\bfrom\s+pickle\s+import", "Import pickle", "Good: standard library", Severity.INFO),
            (r"\bimport\s+shelve\b|\bfrom\s+shelve\s+import", "Import shelve", "Good: standard library", Severity.INFO),
            (r"\bimport\s+sqlite3\b|\bfrom\s+sqlite3\s+import", "Import sqlite3", "Good: standard library", Severity.INFO),
            (r"\bimport\s+ctypes\b|\bfrom\s+ctypes\s+import", "Import ctypes", "Good: standard library", Severity.INFO),
            (r"\bimport\s+zipfile\b|\bfrom\s+zipfile\s+import", "Import zipfile", "Good: standard library", Severity.INFO),
            (r"\bimport\s+tarfile\b|\bfrom\s+tarfile\s+import", "Import tarfile", "Good: standard library", Severity.INFO),
            (r"\bimport\s+gzip\b|\bfrom\s+gzip\s+import", "Import gzip", "Good: standard library", Severity.INFO),
            (r"\bimport\s+bz2\b|\bfrom\s+bz2\s+import", "Import bz2", "Good: standard library", Severity.INFO),
            (r"\bimport\s+lzma\b|\bfrom\s+lzma\s+import", "Import lzma", "Good: standard library", Severity.INFO),
            (r"\bimport\s+shutil\b|\bfrom\s+shutil\s+import", "Import shutil", "Good: standard library", Severity.INFO),
            (r"\bimport\s+glob\b|\bfrom\s+glob\s+import", "Import glob", "Good: standard library", Severity.INFO),
            (r"\bimport\s+fnmatch\b|\bfrom\s+fnmatch\s+import", "Import fnmatch", "Good: standard library", Severity.INFO),
            (r"\bimport\s+tempfile\b|\bfrom\s+tempfile\s+import", "Import tempfile", "Good: standard library", Severity.INFO),
            (r"\bimport\s+os.path\b|\bfrom\s+os.path\s+import", "Import os.path", "Good: standard library", Severity.INFO),
            (r"\bimport\s+platform\b|\bfrom\s+platform\s+import", "Import platform", "Good: standard library", Severity.INFO),
            (r"\bimport\s+signal\b|\bfrom\s+signal\s+import", "Import signal", "Good: standard library", Severity.INFO),
            (r"\bimport\s+mmap\b|\bfrom\s+mmap\s+import", "Import mmap", "Good: standard library", Severity.INFO),
            (r"\bimport\s+codecs\b|\bfrom\s+codecs\s+import", "Import codecs", "Good: standard library", Severity.INFO),
            (r"\bimport\s+encodings\b|\bfrom\s+encodings\s+import", "Import encodings", "Good: standard library", Severity.INFO),
            (r"\bimport\s+unicodedata\b|\bfrom\s+unicodedata\s+import", "Import unicodedata", "Good: standard library", Severity.INFO),
        ]
        for line_num, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped.startswith('#'):
                continue
            for pattern, message, suggestion in patterns:
                if re.search(pattern, line):
                    issues.append(self._create_issue(
                        file_path=file_path, line=line_num, message=message,
                        suggestion=suggestion, severity=Severity.INFO,
                        code_snippet=stripped,
                    ))
        return issues
