"""
Comprehensive Rust-specific rules.
"""
import re
from ..core.models import CodeIssue, Severity, IssueCategory
from ..core.rules import BaseRule


class RustComprehensiveRules(BaseRule):
    @property
    def name(self) -> str:
        return "rust_comprehensive"
    @property
    def description(self) -> str:
        return "Rust-specific comprehensive rules"
    @property
    def category(self) -> IssueCategory:
        return IssueCategory.BEST_PRACTICE
    @property
    def severity(self) -> Severity:
        return Severity.INFO

    def check(self, file_path: str, content: str) -> list[CodeIssue]:
        if not file_path.endswith('.rs'):
            return []
        issues = []
        lines = content.splitlines()
        patterns = [
            (r"fn\s+\w+", "Function definition", "Good: defining functions", Severity.INFO),
            (r"pub\s+fn", "Public function", "Good: public API", Severity.INFO),
            (r"pub\(crate\)\s+fn", "Crate-public function", "Good: visibility control", Severity.INFO),
            (r"pub\(super\)\s+fn", "Parent-public function", "Good: visibility control", Severity.INFO),
            (r"pub\(self\)\s+fn", "Self-public function", "Good: visibility control", Severity.INFO),
            (r"impl\s+\w+", "Impl block", "Good: implementing types", Severity.INFO),
            (r"impl\s+<\w+>\s+\w+", "Generic impl", "Good: generic implementations", Severity.INFO),
            (r"trait\s+\w+", "Trait definition", "Good: defining traits", Severity.INFO),
            (r"pub\s+trait", "Public trait", "Good: public traits", Severity.INFO),
            (r"derive\s*\(", "Derive macro", "Good: deriving traits", Severity.INFO),
            (r"#\[derive\(", "Derive attribute", "Good: using derive macros", Severity.INFO),
            (r"struct\s+\w+", "Struct definition", "Good: defining structs", Severity.INFO),
            (r"enum\s+\w+", "Enum definition", "Good: defining enums", Severity.INFO),
            (r"match\s+\w+", "Match expression", "Good: pattern matching", Severity.INFO),
            (r"if\s+let\s+", "if let", "Good: using if let", Severity.INFO),
            (r"while\s+let\s+", "while let", "Good: using while let", Severity.INFO),
            (r"loop\s*\{", "Loop expression", "Good: using loops", Severity.INFO),
            (r"for\s+\w+\s+in\s+\w+", "For loop", "Good: iterating", Severity.INFO),
            (r"return\s+\w+", "Return statement", "Good: returning values", Severity.INFO),
            (r"Ok\(\w+\)", "Ok variant", "Good: using Ok", Severity.INFO),
            (r"Err\(\w+\)", "Err variant", "Good: using Err", Severity.INFO),
            (r"Some\(\w+\)", "Some variant", "Good: using Some", Severity.INFO),
            (r"None\b", "None value", "Good: handling None", Severity.INFO),
            (r"\.unwrap\(\)", "unwrap() call", "Use .unwrap_or() or proper error handling", Severity.WARNING),
            (r"\.expect\(\s*\"[^\"]+\"\s*\)", "expect() call", "Good: using expect with message", Severity.INFO),
            (r"\.unwrap_or\(", "unwrap_or() call", "Good: providing default", Severity.INFO),
            (r"\.unwrap_or_else\(", "unwrap_or_else() call", "Good: providing default closure", Severity.INFO),
            (r"\.unwrap_or_default\(\)", "unwrap_or_default()", "Good: using default", Severity.INFO),
            (r"\.map\(\|", "map closure", "Good: using map", Severity.INFO),
            (r"\.and_then\(\|", "and_then closure", "Good: chaining operations", Severity.INFO),
            (r"\.ok_or\(", "ok_or call", "Good: converting Option to Result", Severity.INFO),
            (r"\.ok_or_else\(", "ok_or_else call", "Good: converting Option to Result", Severity.INFO),
            (r"\.map_err\(\|", "map_err closure", "Good: mapping errors", Severity.INFO),
            (r"\.filter\(\|", "filter closure", "Good: filtering", Severity.INFO),
            (r"\.fold\(", "fold call", "Good: folding", Severity.INFO),
            (r"\.collect\(\)", "collect call", "Good: collecting", Severity.INFO),
            (r"\.enumerate\(\)", "enumerate call", "Good: enumerating", Severity.INFO),
            (r"\.zip\(", "zip call", "Good: zipping iterators", Severity.INFO),
            (r"\.chain\(", "chain call", "Good: chaining iterators", Severity.INFO),
            (r"\.flat_map\(\|", "flat_map closure", "Good: flat mapping", Severity.INFO),
            (r"\.map_err\(\|", "map_err closure", "Good: mapping errors", Severity.INFO),
            (r"macro_rules!", "Macro definition", "Good: defining macros", Severity.INFO),
            (r"println!\(", "println! macro", "Good: using println!", Severity.INFO),
            (r"print!\(", "print! macro", "Good: using print!", Severity.INFO),
            (r"eprintln!\(", "eprintln! macro", "Good: using eprintln!", Severity.INFO),
            (r"eprint!\(", "eprint! macro", "Good: using eprint!", Severity.INFO),
            (r"format!\(", "format! macro", "Good: using format!", Severity.INFO),
            (r"vec!\[", "vec! macro", "Good: using vec! macro", Severity.INFO),
            (r"vec!\(", "vec! macro", "Good: using vec! macro", Severity.INFO),
            (r"assert!\(", "assert! macro", "Good: using assert!", Severity.INFO),
            (r"assert_eq!\(", "assert_eq! macro", "Good: using assert_eq!", Severity.INFO),
            (r"assert_ne!\(", "assert_ne! macro", "Good: using assert_ne!", Severity.INFO),
            (r"debug_assert!\(", "debug_assert! macro", "Good: using debug_assert!", Severity.INFO),
            (r"debug_assert_eq!\(", "debug_assert_eq! macro", "Good: using debug_assert_eq!", Severity.INFO),
            (r"todo!\(\)", "todo!() call", "Replace with implementation", Severity.WARNING),
            (r"unimplemented!\(\)", "unimplemented!() call", "Replace with implementation", Severity.WARNING),
            (r"unreachable!\(\)", "unreachable!() call", "Good: marking unreachable code", Severity.INFO),
            (r"panic!\(", "panic! macro", "Avoid panic in production", Severity.WARNING),
            (r"dbg!\(", "dbg! macro", "Remove dbg! in production", Severity.INFO),
            (r"const\s+\w+", "Const declaration", "Good: using constants", Severity.INFO),
            (r"static\s+\w+", "Static declaration", "Good: using statics", Severity.INFO),
            (r"lazy_static!", "lazy_static! macro", "Consider using once_cell", Severity.INFO),
            (r"once_cell", "once_cell crate", "Good: using once_cell", Severity.INFO),
            (r"tokio::", "tokio crate", "Good: using tokio", Severity.INFO),
            (r"async\s+fn", "Async function", "Good: using async", Severity.INFO),
            (r"await\s*;", "await expression", "Good: awaiting futures", Severity.INFO),
            (r"select!\{", "select! macro", "Good: selecting futures", Severity.INFO),
            (r"spawn\(", "spawn call", "Good: spawning tasks", Severity.INFO),
            (r"Arc::new\(", "Arc::new", "Good: using Arc", Severity.INFO),
            (r"Mutex::new\(", "Mutex::new", "Good: using Mutex", Severity.INFO),
            (r"RwLock::new\(", "RwLock::new", "Good: using RwLock", Severity.INFO),
            (r"channel\(\)", "channel()", "Good: using channels", Severity.INFO),
            (r"crossbeam", "crossbeam crate", "Good: using crossbeam", Severity.INFO),
            (r"rayon::", "rayon crate", "Good: using rayon", Severity.INFO),
            (r"serde::", "serde crate", "Good: using serde", Severity.INFO),
            (r"#\[serde\(", "serde attribute", "Good: using serde attributes", Severity.INFO),
            (r"tokio::main", "tokio::main", "Good: using tokio runtime", Severity.INFO),
            (r"#\[test\]", "test attribute", "Good: writing tests", Severity.INFO),
            (r"#\[cfg\(test\)\]", "cfg(test) attribute", "Good: test module", Severity.INFO),
            (r"#\[bench\]", "bench attribute", "Good: writing benchmarks", Severity.INFO),
            (r"cargo test", "cargo test", "Good: running tests", Severity.INFO),
            (r"cargo clippy", "cargo clippy", "Good: using clippy", Severity.INFO),
            (r"cargo fmt", "cargo fmt", "Good: formatting code", Severity.INFO),
            (r"unsafe\s*\{", "unsafe block", "Minimize unsafe code", Severity.WARNING),
            (r"unsafe\s+fn", "unsafe function", "Minimize unsafe functions", Severity.WARNING),
            (r"as\s+\w+", "Type cast", "Use explicit conversions", Severity.INFO),
            (r"transmute\(", "transmute call", "Avoid transmute", Severity.WARNING),
            (r"raw\s+pointer", "Raw pointer", "Minimize raw pointer use", Severity.WARNING),
            (r"extern\s+\"C\"", "extern \"C\"", "Good: FFI declaration", Severity.INFO),
            (r"PhantomData", "PhantomData", "Good: using PhantomData", Severity.INFO),
            (r"Pin::new\(", "Pin::new", "Good: pinning values", Severity.INFO),
            (r"Box::new\(", "Box::new", "Good: heap allocation", Severity.INFO),
            (r"Rc::new\(", "Rc::new", "Good: reference counting", Severity.INFO),
            (r"Arc::new\(", "Arc::new", "Good: atomic reference counting", Severity.INFO),
            (r"Cell::new\(", "Cell::new", "Good: interior mutability", Severity.INFO),
            (r"RefCell::new\(", "RefCell::new", "Good: runtime borrow checking", Severity.INFO),
            (r"HashMap::new\(", "HashMap::new", "Good: using HashMap", Severity.INFO),
            (r"BTreeMap::new\(", "BTreeMap::new", "Good: using BTreeMap", Severity.INFO),
            (r"Vec::new\(", "Vec::new", "Good: creating vectors", Severity.INFO),
            (r"VecDeque::new\(", "VecDeque::new", "Good: using VecDeque", Severity.INFO),
            (r"String::new\(", "String::new", "Good: creating strings", Severity.INFO),
            (r"to_string\(\)", "to_string()", "Good: converting to string", Severity.INFO),
            (r"to_owned\(\)", "to_owned()", "Good: converting to owned", Severity.INFO),
            (r"clone\(\)", "clone() call", "Avoid unnecessary cloning", Severity.INFO),
            (r"copy\(\)", "copy() call", "Good: copying Copy types", Severity.INFO),
            (r"into\(\)", "into() call", "Good: type conversion", Severity.INFO),
            (r"as_ref\(\)", "as_ref() call", "Good: borrowing as ref", Severity.INFO),
            (r"as_mut\(\)", "as_mut() call", "Good: borrowing as mutable", Severity.INFO),
            (r"deref\(\)", "deref() call", "Good: dereferencing", Severity.INFO),
            (r"iter\(\)", "iter() call", "Good: iterating", Severity.INFO),
            (r"iter_mut\(\)", "iter_mut() call", "Good: mutable iteration", Severity.INFO),
            (r"into_iter\(\)", "into_iter() call", "Good: consuming iteration", Severity.INFO),
            (r"len\(\)", "len() call", "Good: checking length", Severity.INFO),
            (r"is_empty\(\)", "is_empty() call", "Good: checking emptiness", Severity.INFO),
            (r"push\(", "push() call", "Good: adding elements", Severity.INFO),
            (r"pop\(\)", "pop() call", "Good: removing elements", Severity.INFO),
            (r"insert\(", "insert() call", "Good: inserting elements", Severity.INFO),
            (r"remove\(", "remove() call", "Good: removing elements", Severity.INFO),
            (r"contains\(", "contains() call", "Good: checking containment", Severity.INFO),
            (r"get\(", "get() call", "Good: safe indexing", Severity.INFO),
            (r"entry\(", "entry() call", "Good: using entry API", Severity.INFO),
            (r"or_insert\(", "or_insert() call", "Good: default insertion", Severity.INFO),
            (r"or_insert_with\(", "or_insert_with() call", "Good: default insertion", Severity.INFO),
            (r"and_modify\(", "and_modify() call", "Good: modifying entry", Severity.INFO),
            (r"#\[derive\(", "Derive attribute", "Good: deriving traits", Severity.INFO),
            (r"#\[allow\(", "allow attribute", "Good: suppressing warnings", Severity.INFO),
            (r"#\[warn\(", "warn attribute", "Good: configuring warnings", Severity.INFO),
            (r"#\[deny\(", "deny attribute", "Good: enforcing rules", Severity.INFO),
            (r"#\[forbid\(", "forbid attribute", "Good: forbidding patterns", Severity.INFO),
            (r"#\[must_use\]", "must_use attribute", "Good: requiring use of return", Severity.INFO),
            (r"#\[inline\(", "inline attribute", "Good: controlling inlining", Severity.INFO),
            (r"#\[cold\]", "cold attribute", "Good: marking cold paths", Severity.INFO),
            (r"#\[repr\(", "repr attribute", "Good: controlling layout", Severity.INFO),
            (r"#\[doc\(", "doc attribute", "Good: documenting code", Severity.INFO),
            (r"#\[cfg\(", "cfg attribute", "Good: conditional compilation", Severity.INFO),
            (r"use\s+\w+", "Use statement", "Good: importing", Severity.INFO),
            (r"mod\s+\w+", "Module declaration", "Good: organizing modules", Severity.INFO),
            (r"pub\s+mod", "Public module", "Good: public modules", Severity.INFO),
            (r"pub\s+use", "Public use", "Good: re-exporting", Severity.INFO),
            (r"pub\s+struct", "Public struct", "Good: public types", Severity.INFO),
            (r"pub\s+enum", "Public enum", "Good: public enums", Severity.INFO),
            (r"pub\s+trait", "Public trait", "Good: public traits", Severity.INFO),
            (r"pub\s+type", "Public type alias", "Good: type aliases", Severity.INFO),
            (r"pub\s+const", "Public constant", "Good: public constants", Severity.INFO),
            (r"pub\s+static", "Public static", "Good: public statics", Severity.INFO),
            (r"pub\s+async", "Public async", "Good: public async functions", Severity.INFO),
            (r"pub\s+extern", "Public extern", "Good: public FFI", Severity.INFO),
            (r"impl\s+Drop", "Drop implementation", "Good: cleanup", Severity.INFO),
            (r"impl\s+Clone", "Clone implementation", "Good: cloning support", Severity.INFO),
            (r"impl\s+Copy", "Copy implementation", "Good: copy semantics", Severity.INFO),
            (r"impl\s+Debug", "Debug implementation", "Good: debug output", Severity.INFO),
            (r"impl\s+Display", "Display implementation", "Good: display output", Severity.INFO),
            (r"impl\s+From<", "From implementation", "Good: type conversion", Severity.INFO),
            (r"impl\s+Into<", "Into implementation", "Good: type conversion", Severity.INFO),
            (r"impl\s+TryFrom<", "TryFrom implementation", "Good: fallible conversion", Severity.INFO),
            (r"impl\s+TryInto<", "TryInto implementation", "Good: fallible conversion", Severity.INFO),
            (r"impl\s+Default", "Default implementation", "Good: default values", Severity.INFO),
            (r"impl\s+Iterator", "Iterator implementation", "Good: custom iterators", Severity.INFO),
            (r"impl\s+Display\s+for", "Display for", "Good: formatting types", Severity.INFO),
            (r"impl\s+Debug\s+for", "Debug for", "Good: debugging types", Severity.INFO),
            (r"impl\s+PartialEq", "PartialEq implementation", "Good: equality comparison", Severity.INFO),
            (r"impl\s+Eq", "Eq implementation", "Good: equivalence", Severity.INFO),
            (r"impl\s+PartialOrd", "PartialOrd implementation", "Good: ordering", Severity.INFO),
            (r"impl\s+Ord", "Ord implementation", "Good: total ordering", Severity.INFO),
            (r"impl\s+Hash", "Hash implementation", "Good: hashing", Severity.INFO),
            (r"impl\s+AsRef<", "AsRef implementation", "Good: borrowing", Severity.INFO),
            (r"impl\s+Deref<", "Deref implementation", "Good: deref coercion", Severity.INFO),
            (r"impl\s+DerefMut<", "DerefMut implementation", "Good: mutable deref", Severity.INFO),
            (r"impl\s+Borrow<", "Borrow implementation", "Good: borrowing", Severity.INFO),
            (r"impl\s+Sized", "Sized implementation", "Good: sized types", Severity.INFO),
            (r"impl\s+Send", "Send implementation", "Good: thread safety", Severity.INFO),
            (r"impl\s+Sync", "Sync implementation", "Good: thread safety", Severity.INFO),
            (r"impl\s+Unpin", "Unpin implementation", "Good: pinning support", Severity.INFO),
            (r"impl\s+Future", "Future implementation", "Good: async support", Severity.INFO),
            (r"impl\s+AsyncIterator", "AsyncIterator implementation", "Good: async iteration", Severity.INFO),
            (r"impl\s+AsyncRead", "AsyncRead implementation", "Good: async reading", Severity.INFO),
            (r"impl\s+AsyncWrite", "AsyncWrite implementation", "Good: async writing", Severity.INFO),
            (r"impl\s+AsyncBufRead", "AsyncBufRead implementation", "Good: async buffered reading", Severity.INFO),
            (r"impl\s+Read", "Read implementation", "Good: reading", Severity.INFO),
            (r"impl\s+Write", "Write implementation", "Good: writing", Severity.INFO),
            (r"impl\s+BufRead", "BufRead implementation", "Good: buffered reading", Severity.INFO),
            (r"impl\s+Seek", "Seek implementation", "Good: seeking", Severity.INFO),
            (r"impl\s+io::Read", "io::Read implementation", "Good: I/O reading", Severity.INFO),
            (r"impl\s+io::Write", "io::Write implementation", "Good: I/O writing", Severity.INFO),
            (r"impl\s+io::BufRead", "io::BufRead implementation", "Good: I/O buffered reading", Severity.INFO),
            (r"impl\s+io::Seek", "io::Seek implementation", "Good: I/O seeking", Severity.INFO),
            (r"#\[cfg(test)\]", "Test module", "Good: test organization", Severity.INFO),
            (r"#\[test\]", "Test function", "Good: writing tests", Severity.INFO),
            (r"#\[should_panic\]", "should_panic test", "Good: testing panics", Severity.INFO),
            (r"assert!\(", "assert! macro", "Good: asserting", Severity.INFO),
            (r"assert_eq!\(", "assert_eq! macro", "Good: asserting equality", Severity.INFO),
            (r"assert_ne!\(", "assert_ne! macro", "Good: asserting inequality", Severity.INFO),
            (r"debug_assert!\(", "debug_assert! macro", "Good: debug assertions", Severity.INFO),
            (r"debug_assert_eq!\(", "debug_assert_eq! macro", "Good: debug assertions", Severity.INFO),
            (r"cargo doc", "cargo doc", "Good: generating docs", Severity.INFO),
            (r"rustdoc", "rustdoc", "Good: documenting", Severity.INFO),
            (r"///\s+", "Doc comment", "Good: documenting", Severity.INFO),
            (r"//!\s+", "Module doc comment", "Good: module documentation", Severity.INFO),
        ]
        for line_num, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped.startswith('//'):
                continue
            for pattern, message, severity in [(p, m, s) for p, m, _, s in patterns]:
                if re.search(pattern, line):
                    sug = [s2 for p2, m2, s2, _ in patterns if p2 == pattern and m2 == message]
                    issues.append(self._create_issue(
                        file_path=file_path, line=line_num, message=message,
                        suggestion=sug[0] if sug else "", severity=severity, code_snippet=stripped,
                    ))
        return issues
